### ISSUE TITLE
Incorrect Slot Duration Returned

### ISSUE THREAD

**Issue by shayes-phreesia** [athenahealth/apiserver-athenaFlex#147]
**Describe the bug**
We are finding all slots returned with a duration of 15 minutes even though we can see in the UI that slots are available for 30 minutes (see attached)

**To Reproduce**
1. Create a schedule template with both 15 and 30 minute intervals available.
2. Query slots over a date range and slot-type (appointment type)

**Expected behavior**
1. Matching Slots should be returned with the correct duration.

Request:
`GET /demo_cpsAPIServer/fhir/Slot?_summary=data&start=ge2020-07-07T02%3a00%3a00.000-04%3a00&start=le2020-07-07T19%3a59%3a00.000-04%3a00&slot-type=1 HTTP/1.1 `

Response:
`{"resourceType":"Bundle","id":"1.2.840.113619.21.1.8899560752578716278.10.1594057739054.587947","meta":{"lastUpdated":"2020-07-06T13:48:59.054-04:00","tag":[{"system":"http://hl7.org/fhir/v3/ObservationValue","code":"SUBSETTED","display":"Resource encoded in summary mode"}]},"type":"searchset","total":10,"link":[{"relation":"self","url":"http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Slot?_summary=data&slot-type=1&start=ge2020-07-07T02%3A00%3A00.000-04%3A00&start=le2020-07-07T19%3A59%3A00.000-04%3A00"}],"entry":[{"fullUrl":"http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Slot/953192","resource":{"resourceType":"Slot","id":"953192","meta":{"tag":[{"system":"http://hl7.org/fhir/v3/ObservationValue","code":"SUBSETTED","display":"Resource encoded in summary mode"}]},"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-slot-facility","valueString":"3"}],"identifier":[{"type":{"coding":[{"system":"http://hl7.org/fhir/v2/0203","code":"U","display":"Unspecified Identifier"}],"text":"Unspecified Identifier"},"system":"http://www.gehealthcare.com/fhir/cpsemr/namingsystem/SlotId/Training042","value":"953192"}],"type":{"coding":[{"system":"http://hl7.org/fhir/StructureDefinition/ge-appointment-APPTDEF","code":"1","display":"New Patient - 30"}],"text":"New Patient - 30"},"schedule":{"reference":"Schedule/83"},"freeBusyType":"free","_freeBusyType":{"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-originalCode","valueCoding":{"system":"http://www.gehealthcare.com/fhir/cpsemr/codesystem/slotstatus","code":"0","display":"Available"}}]},"start":"2020-07-07T10:30:00.000-04:00","end":"2020-07-07T10:45:00.000-04:00","overbooked":false},"search":{"mode":"match"}},{"fullUrl":"http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Slot/953191","resource":{"resourceType":"Slot","id":"953191","meta":{"tag":[{"system":"http://hl7.org/fhir/v3/ObservationValue","code":"SUBSETTED","display":"Resource encoded in summary mode"}]},"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-slot-facility","valueString":"3"}],"identifier":[{"type":{"coding":[{"system":"http://hl7.org/fhir/v2/0203","code":"U","display":"Unspecified Identifier"}],"text":"Unspecified Identifier"},"system":"http://www.gehealthcare.com/fhir/cpsemr/namingsystem/SlotId/Training042","value":"953191"}],"type":{"coding":[{"system":"http://hl7.org/fhir/StructureDefinition/ge-appointment-APPTDEF","code":"1","display":"New Patient - 30"}],"text":"New Patient - 30"},"schedule":{"reference":"Schedule/83"},"freeBusyType":"free","_freeBusyType":{"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-originalCode","valueCoding":{"system":"http://www.gehealthcare.com/fhir/cpsemr/codesystem/slotstatus","code":"0","display":"Available"}}]},"start":"2020-07-07T10:30:00.000-04:00","end":"2020-07-07T10:45:00.000-04:00","overbooked":false},"search":{"mode":"match"}},{"fullUrl":"http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Slot/953184","resource":{"resourceType":"Slot","id":"953184","meta":{"tag":[{"system":"http://hl7.org/fhir/v3/ObservationValue","code":"SUBSETTED","display":"Resource encoded in summary mode"}]},"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-slot-facility","valueString":"3"}],"identifier":[{"type":{"coding":[{"system":"http://hl7.org/fhir/v2/0203","code":"U","display":"Unspecified Identifier"}],"text":"Unspecified Identifier"},"system":"http://www.gehealthcare.com/fhir/cpsemr/namingsystem/SlotId/Training042","value":"953184"}],"type":{"coding":[{"system":"http://hl7.org/fhir/StructureDefinition/ge-appointment-APPTDEF","code":"1","display":"New Patient - 30"}],"text":"New Patient - 30"},"schedule":{"reference":"Schedule/83"},"freeBusyType":"free","_freeBusyType":{"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-originalCode","valueCoding":{"system":"http://www.gehealthcare.com/fhir/cpsemr/codesystem/slotstatus","code":"0","display":"Available"}}]},"start":"2020-07-07T09:30:00.000-04:00","end":"2020-07-07T09:45:00.000-04:00","overbooked":false},"search":{"mode":"match"}},{"fullUrl":"http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Slot/953183","resource":{"resourceType":"Slot","id":"953183","meta":{"tag":[{"system":"http://hl7.org/fhir/v3/ObservationValue","code":"SUBSETTED","display":"Resource encoded in summary mode"}]},"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-slot-facility","valueString":"3"}],"identifier":[{"type":{"coding":[{"system":"http://hl7.org/fhir/v2/0203","code":"U","display":"Unspecified Identifier"}],"text":"Unspecified Identifier"},"system":"http://www.gehealthcare.com/fhir/cpsemr/namingsystem/SlotId/Training042","value":"953183"}],"type":{"coding":[{"system":"http://hl7.org/fhir/StructureDefinition/ge-appointment-APPTDEF","code":"1","display":"New Patient - 30"}],"text":"New Patient - 30"},"schedule":{"reference":"Schedule/83"},"freeBusyType":"free","_freeBusyType":{"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-originalCode","valueCoding":{"system":"http://www.gehealthcare.com/fhir/cpsemr/codesystem/slotstatus","code":"0","display":"Available"}}]},"start":"2020-07-07T09:30:00.000-04:00","end":"2020-07-07T09:45:00.000-04:00","overbooked":false},"search":{"mode":"match"}},{"fullUrl":"http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Slot/953175","resource":{"resourceType":"Slot","id":"953175","meta":{"tag":[{"system":"http://hl7.org/fhir/v3/ObservationValue","code":"SUBSETTED","display":"Resource encoded in summary mode"}]},"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-slot-facility","valueString":"3"}],"identifier":[{"type":{"coding":[{"system":"http://hl7.org/fhir/v2/0203","code":"U","display":"Unspecified Identifier"}],"text":"Unspecified Identifier"},"system":"http://www.gehealthcare.com/fhir/cpsemr/namingsystem/SlotId/Training042","value":"953175"}],"type":{"coding":[{"system":"http://hl7.org/fhir/StructureDefinition/ge-appointment-APPTDEF","code":"1","display":"New Patient - 30"}],"text":"New Patient - 30"},"schedule":{"reference":"Schedule/83"},"freeBusyType":"free","_freeBusyType":{"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-originalCode","valueCoding":{"system":"http://www.gehealthcare.com/fhir/cpsemr/codesystem/slotstatus","code":"0","display":"Available"}}]},"start":"2020-07-07T07:30:00.000-04:00","end":"2020-07-07T07:45:00.000-04:00","overbooked":false},"search":{"mode":"match"}},{"fullUrl":"http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Slot/916511","resource":{"resourceType":"Slot","id":"916511","meta":{"tag":[{"system":"http://hl7.org/fhir/v3/ObservationValue","code":"SUBSETTED","display":"Resource encoded in summary mode"}]},"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-slot-facility","valueString":"3"}],"identifier":[{"type":{"coding":[{"system":"http://hl7.org/fhir/v2/0203","code":"U","display":"Unspecified Identifier"}],"text":"Unspecified Identifier"},"system":"http://www.gehealthcare.com/fhir/cpsemr/namingsystem/SlotId/Training042","value":"916511"}],"type":{"coding":[{"system":"http://hl7.org/fhir/StructureDefinition/ge-appointment-APPTDEF","code":"1","display":"New Patient - 30"}],"text":"New Patient - 30"},"schedule":{"reference":"Schedule/73"},"freeBusyType":"free","_freeBusyType":{"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-originalCode","valueCoding":{"system":"http://www.gehealthcare.com/fhir/cpsemr/codesystem/slotstatus","code":"0","display":"Available"}}]},"start":"2020-07-07T10:30:00.000-04:00","end":"2020-07-07T10:45:00.000-04:00","overbooked":false},"search":{"mode":"match"}},{"fullUrl":"http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Slot/916510","resource":{"resourceType":"Slot","id":"916510","meta":{"tag":[{"system":"http://hl7.org/fhir/v3/ObservationValue","code":"SUBSETTED","display":"Resource encoded in summary mode"}]},"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-slot-facility","valueString":"3"}],"identifier":[{"type":{"coding":[{"system":"http://hl7.org/fhir/v2/0203","code":"U","display":"Unspecified Identifier"}],"text":"Unspecified Identifier"},"system":"http://www.gehealthcare.com/fhir/cpsemr/namingsystem/SlotId/Training042","value":"916510"}],"type":{"coding":[{"system":"http://hl7.org/fhir/StructureDefinition/ge-appointment-APPTDEF","code":"1","display":"New Patient - 30"}],"text":"New Patient - 30"},"schedule":{"reference":"Schedule/73"},"freeBusyType":"free","_freeBusyType":{"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-originalCode","valueCoding":{"system":"http://www.gehealthcare.com/fhir/cpsemr/codesystem/slotstatus","code":"0","display":"Available"}}]},"start":"2020-07-07T10:30:00.000-04:00","end":"2020-07-07T10:45:00.000-04:00","overbooked":false},"search":{"mode":"match"}},{"fullUrl":"http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Slot/916503","resource":{"resourceType":"Slot","id":"916503","meta":{"tag":[{"system":"http://hl7.org/fhir/v3/ObservationValue","code":"SUBSETTED","display":"Resource encoded in summary mode"}]},"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-slot-facility","valueString":"3"}],"identifier":[{"type":{"coding":[{"system":"http://hl7.org/fhir/v2/0203","code":"U","display":"Unspecified Identifier"}],"text":"Unspecified Identifier"},"system":"http://www.gehealthcare.com/fhir/cpsemr/namingsystem/SlotId/Training042","value":"916503"}],"type":{"coding":[{"system":"http://hl7.org/fhir/StructureDefinition/ge-appointment-APPTDEF","code":"1","display":"New Patient - 30"}],"text":"New Patient - 30"},"schedule":{"reference":"Schedule/73"},"freeBusyType":"free","_freeBusyType":{"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-originalCode","valueCoding":{"system":"http://www.gehealthcare.com/fhir/cpsemr/codesystem/slotstatus","code":"0","display":"Available"}}]},"start":"2020-07-07T09:30:00.000-04:00","end":"2020-07-07T09:45:00.000-04:00","overbooked":false},"search":{"mode":"match"}},{"fullUrl":"http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Slot/916502","resource":{"resourceType":"Slot","id":"916502","meta":{"tag":[{"system":"http://hl7.org/fhir/v3/ObservationValue","code":"SUBSETTED","display":"Resource encoded in summary mode"}]},"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-slot-facility","valueString":"3"}],"identifier":[{"type":{"coding":[{"system":"http://hl7.org/fhir/v2/0203","code":"U","display":"Unspecified Identifier"}],"text":"Unspecified Identifier"},"system":"http://www.gehealthcare.com/fhir/cpsemr/namingsystem/SlotId/Training042","value":"916502"}],"type":{"coding":[{"system":"http://hl7.org/fhir/StructureDefinition/ge-appointment-APPTDEF","code":"1","display":"New Patient - 30"}],"text":"New Patient - 30"},"schedule":{"reference":"Schedule/73"},"freeBusyType":"free","_freeBusyType":{"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-originalCode","valueCoding":{"system":"http://www.gehealthcare.com/fhir/cpsemr/codesystem/slotstatus","code":"0","display":"Available"}}]},"start":"2020-07-07T09:30:00.000-04:00","end":"2020-07-07T09:45:00.000-04:00","overbooked":false},"search":{"mode":"match"}},{"fullUrl":"http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Slot/916494","resource":{"resourceType":"Slot","id":"916494","meta":{"tag":[{"system":"http://hl7.org/fhir/v3/ObservationValue","code":"SUBSETTED","display":"Resource encoded in summary mode"}]},"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-slot-facility","valueString":"3"}],"identifier":[{"type":{"coding":[{"system":"http://hl7.org/fhir/v2/0203","code":"U","display":"Unspecified Identifier"}],"text":"Unspecified Identifier"},"system":"http://www.gehealthcare.com/fhir/cpsemr/namingsystem/SlotId/Training042","value":"916494"}],"type":{"coding":[{"system":"http://hl7.org/fhir/StructureDefinition/ge-appointment-APPTDEF","code":"1","display":"New Patient - 30"}],"text":"New Patient - 30"},"schedule":{"reference":"Schedule/73"},"freeBusyType":"free","_freeBusyType":{"extension":[{"url":"http://hl7.org/fhir/StructureDefinition/ge-originalCode","valueCoding":{"system":"http://www.gehealthcare.com/fhir/cpsemr/codesystem/slotstatus","code":"0","display":"Available"}}]},"start":"2020-07-07T07:30:00.000-04:00","end":"2020-07-07T07:45:00.000-04:00","overbooked":false},"search":{"mode":"match"}}]} 
 `

**Screenshots**
![image](https://user-images.githubusercontent.com/60858694/88000153-fae90080-caca-11ea-9c0d-3923bed1ecb6.png)

**Comment by AjeetYadav07** [comment]
Thanks for making us aware of the issue. It is under investigation to determine the required solution.

**Comment by shayes-phreesia** [comment]
I was told this would be in v20 sp1 - any update on when this would be released?

**Comment by AjeetYadav07** [comment]
Can you please connect with your CSM to get updates on V20_sp1.

**Comment by shayes-phreesia** [comment]
after applying v20 sp1 fix in dev environment we found that the correct slot is returned but on appointment booking (Appointment Create) it is still expecting incorrect slot time. 

Response:
{"resourceType":"OperationOutcome","text":{"status":"generated","div":"<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Outcome null</span></td><td width=\"42%\"><span class=\"text-muted\"><table><thead><tr><th>#</th><th>Severity</th><th>Type</th><th>Detail</th></tr></thead><tbody><tr><td>1</td><td>FATAL</td><td>EXCEPTION</td><td>No slot found for given details to create appointment.</td></tr></tbody></table></span></td></tr></tbody></table></div>"},"issue":[{"severity":"fatal","code":"exception","diagnostics":"No slot found for given details to create appointment."}]}

**Comment by AjeetYadav07** [comment]
Can you please share more detailed about the issue like payload?

**Comment by shayes-phreesia** [comment]
@AjeetYadav07  this is request to book appointment in the slot we get back from open slots search:

POST http://cps.phreesia.me:9080/demo_cpsAPIServer/fhir/Appointment?_summary=data HTTP/1.1
Accept: application/json, application/json+fhir
Accept-Charset: utf-8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlNzWnNCTmhaY0YzUTlTNHRycFFCVEJ5TlJSSSIsImtpZCI6IlNzWnNCTmhaY0YzUTlTNHRycFFCVEJ5TlJSSSJ9.eyJhdWQiOiIyODFmOTIwMi04OGVlLTQyN2UtYWQyZi1jMDE1MjY3ZTQyZmEiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8yNzRjOTA0Zi05N2MwLTRkN2YtOGY4NC04MDUwMmJmZTVmNmYvIiwiaWF0IjoxNTk0MDU3NDY1LCJuYmYiOjE1OTQwNTc0NjUsImV4cCI6MTU5NDA2MTM2NSwiYWNyIjoiMSIsImFpbyI6IkFTUUEyLzhRQUFBQU5DUCtuQjcyYUsvZE5EMk9qMVAwNzQ3R0U4cjVVaXJINVFUVmp2VHRCTEE9IiwiYW1yIjpbInB3ZCJdLCJhcHBpZCI6ImVmOGZlN2E4LTBlYTAtNGMzNC1hOTg2LTAzMTIwY2QzMzk2ZiIsImFwcGlkYWNyIjoiMCIsImZhbWlseV9uYW1lIjoiV2luc3RvbiIsImdpdmVuX25hbWUiOiJIYXJyeSIsImlwYWRkciI6IjM0LjIwMC4xMjMuNjEiLCJuYW1lIjoiSGFycnkgV2luc3RvbiIsIm9pZCI6ImE5MDRiNTY0LWRkNDktNDM3Yi1hYTM2LTQ5ZDRmNzU5ZGQ5ZCIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6ImdWQ0xzVUhzSkZJeVBmdG16TFNYNkFHb1ViNFR5R1FaLVdITWUzOTRSNkUiLCJ0aWQiOiIyNzRjOTA0Zi05N2MwLTRkN2YtOGY4NC04MDUwMmJmZTVmNmYiLCJ1bmlxdWVfbmFtZSI6Imh3aW5zdG9uQGZoaXJwcm92aWRlcmIyYi5vbm1pY3Jvc29mdC5jb20iLCJ1cG4iOiJod2luc3RvbkBmaGlycHJvdmlkZXJiMmIub25taWNyb3NvZnQuY29tIiwidXRpIjoiVmhNSFJwVFFIa2lVcWdSd2JNWmlBQSIsInZlciI6IjEuMCJ9.AwnW58gGMPZhbZJhT1sXj1iYE2XbVuV4CI9NHT14HBWk7Gm2icjMnuvrtEcz1KgVU9Cy75XGArQeCcJzoBy2omMw63pvn-ASpsfA4oi9i9-uGkWJozt-BIP4T20nLPNpWpH1eR6BrMc8Ijo1WoUxnAO8RWYTz-Zb9fC9Eh5Nklr1V7aTzYs5PWzlywWwQlYs-bK2iJSbeLQOxgmFwVrtAiY3K0ANS2F5pFLAIzbcsPiDPs4uaLxl1M0TWbMxKzJ_Y4xOpNY6jjeQkqHC6m0i9cmv-bSNjosT4_5-sybwOcmdDnC3_yxOmGdrYCa4QNRiIqQkAP7oh0J0qt_MKII1sA~~34510a6d022abd152dbfd6659164e71960284fefc54fed6400dbe320fd9be0c29867efd6ccdaefac891b4b04ac22738992ffed7a0b9d1729a537adabb7d3c2ca
Content-Type: application/json+fhir; charset=utf-8
Host: cps.phreesia.me:9080
Cookie: JSESSIONID=ZjREP78CptG0JpXgvFHmQJS3d7m_-AzjpUczOrIm.EEAZCPSSQL301
Content-Length: 450
Expect: 100-continue{"end":"2020-07-06T08:00:00.000-04:00","minutesDuration":30,"start":"2020-07-06T07:30:00.000-04:00","participant":[{"actor":{"reference":"Patient/1442678381100620"}},{"actor":{"reference":"Practitioner/1588761792000070"}},{"actor":{"reference":"Location/FAC-3"}}],"description":"test","type":{"coding":[{"system":"http://hl7.org/fhir/StructureDefinition/ge-appointment-APPTDEF","code":"1","display":"New Patient - 30"}]},"resourceType":"Appointment"} 

Response:

 HTTP/1.1 400 Bad Request
Connection: keep-alive
Cache-Control: no-cache, no-store
Server: JBoss-EAP/7
Pragma: no-cache
Content-Type: application/json+fhir; charset=UTF-8
Date: Mon, 06 Jul 2020 17:52:24 GMT
Content-Length: 648{"resourceType":"OperationOutcome","text":{"status":"generated","div":"<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Outcome null</span></td><td width=\"42%\"><span class=\"text-muted\"><table><thead><tr><th>#</th><th>Severity</th><th>Type</th><th>Detail</th></tr></thead><tbody><tr><td>1</td><td>FATAL</td><td>EXCEPTION</td><td>No slot found for given details to create appointment.</td></tr></tbody></table></span></td></tr></tbody></table></div>"},"issue":[{"severity":"fatal","code":"exception","diagnostics":"No slot found for given details to create appointment."}]}

**Comment by AjeetYadav07** [comment]
By following steps able to create Appointment : 
1. create a schedule for appointment in client.
2.  create appointment for respective schedule using post call.  Attaching sample payload for same.
                        [POST] https://localhost:9443/CentricityPracticeFHIRServer/fhir/Appointment

[Appointment_createPayload.txt](https://github.com/virencehealth/apiserver.virencehealth.com/files/5333812/Appointment_createPayload.txt)

3. Put the slot time which is available to create an appointment. 
please look at snapshot attached.

![appt22](https://user-images.githubusercontent.com/68940876/95205029-758c0700-0802-11eb-9819-1ea7d3eb760f.png)

![appt33](https://user-images.githubusercontent.com/68940876/95205040-77ee6100-0802-11eb-8a01-90857ebfbad5.png)

**Comment by shayes-phreesia** [comment]
Hi, this is not the problem. Problem occurs when trying to book in a slot for 30 minutes like the one in your screenshot for new patients. Even though the slot is for 30 minutes and is returned correctly, it only allows booking for 15 minutes

**Comment by shayes-phreesia** [comment]
the appointment type is meant to be scheduled in 30 minute slots but only 15 minutes in duration is allowed as per your attachment @AjeetYadav07

**Comment by AjeetYadav07** [comment]
Hi,
The fix related to this issue will be available in future releases, we have **Appointment** resource in new version of FHIR R4 implemented as part of our future release.

**Comment by AjeetYadav07** [comment]
Closing this issue, if you have any query please raise a new ticket.
