### ISSUE TITLE
The payer id  specified for type patient doesn't exists in the system

### ISSUE THREAD

**Issue by rahul-chetu** [athenahealth/apiserver-athenaFlex#158]
What is the payer id for payment postback?

we have tried the below examples with the given payload, it's working as expected for the test account but not in live.
Currently, we are passing PatientProfileId as payer id.
We are getting the below error:-
"severity": "error",
 "code": "business-rule",
 "diagnostics": "The payer id  specified for type patient doesn't exist in the system"

**Comment by AjeetYadav07** [comment]
With payload we suppose to pass the patient reference as well to match with payerId. In the below payload contains reference to the patient.  

[postpayment.txt](https://github.com/virencehealth/apiserver.virencehealth.com/files/5473388/postpayment.txt)

**Comment by rahul-chetu** [comment]
Hi @AjeetYadav07, 
We added the patient reference as suggested, but we are still getting the same error (The payer id specified for type patient doesn't exist in the system). The same works well in test/ staging, but not in production. 
If we remove the payer id, it says it is mandatory. if we send the payer id, it says does not match and gives error (The payer id specified for type patient doesn't exist in the system). If we add patient reference, then also we get the same error (The payer id specified for type patient doesn't exist in the system).
Please advice :-
![image](https://user-images.githubusercontent.com/61985382/97868191-44392500-1d35-11eb-9675-efbb121a7d75.png)

**Comment by AjeetYadav07** [comment]
1009843200000000 is accepted as a PayerId for posting payments in cpsapisandbox because this value is a valid Patient.id
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Patient/1009843200000000
At this time, PayerId must be a valid FHIR Patient.id value when PayerType is Patient in the body of $PostPayment request.

**Comment by rahul-chetu** [comment]
Hi @AjeetYadav07 ,

We are passing Patient.id but still getting the same error.

**Comment by rahul-chetu** [comment]
Hi @AjeetYadav07 
Is it possible to get on a call to discuss this? I think that will make things easier.
Please let us know a suitable time based on your availability if that is possible.

**Comment by Torin-Shepard-athena** [comment]
@rahul-chetu Please send email to athenaInterop@athenahealth.com with your time zone so we can contact you through email to arrange a session with you sharing your screen so we can investigate this issue with you.

**Comment by AjeetYadav07** [comment]
Closing this issue, if you have any query please raise a new ticket.

**Comment by Torin-Shepard-athena** [comment]
In future releases, the PayerId values in $PostPayment request body must be PatientProfileId values.

These values can be obtained from Patient resource.identifier where system ends with "namingsystem/PatientId/Training".

                <identifier>
                    <type>
                        <coding>
                            <system value="http://hl7.org/fhir/v2/0203"/>
                            <code value="PI"/>
                        </coding>
                    </type>
                    <system value="http://www.gehealthcare.com/fhir/cpsemr/namingsystem/PatientId/Training"/>
                    <value value="367"/>
                </identifier>
