### ISSUE TITLE
Service Applications in the sandbox?

### ISSUE THREAD

**Issue by nerdyworm** [athenahealth/apiserver-athenaFlex#170]
Good Afternoon,

The documentation eludes to being able to generate an access token with the client credentials oauth flow as define by [RFC 6749](https://tools.ietf.org/html/rfc6749#section-4.4)

Is this flow available anywhere?  Our application is designed to work without user interaction.

Thanks,
Ben

**Comment by AjeetYadav07** [comment]
Good Morning ,

 to generate a authorization token we have to workflows.
1.Patient workflow: Generate authorization code using Personal account
Personal account - Use personal account if you are building patient facing application where patients will use their login credentials.
2.Provider workflow: Generate authorization code using Work account
Work account - Use work account if you are building provider facing applications or applications that are used by users belonging to a clinic or a practice.

**Comment by ARCSIndia** [comment]
I am able to access API, but once Access Token expire, Needs to e-generate an authorization code again and again manually?

The authorization code through exception when sending message on Re-Generation of token using same authorization code
"error_description": "User session not found. User must re-authenticate."

On every 60 minutes I have to manually re-generate an authorization code using Construct the Access My Data URL.

I have created a job, which reads data using API on daily basis. Once token expire, what's the best way to re-generate the token through code. 

Thanks,
Pankaj

**Comment by AjeetYadav07** [comment]
@ARCSIndia Closing this issue, Since it is already addressed in #173
