### ISSUE TITLE
Why is the sandbox trying to POST the authorization code to my client?

### ISSUE THREAD

**Issue by dwwinters** [athenahealth/apiserver-athenaFlex#172]
**Your question**

After completing the "Provider workflow: Generate authorization code using Work account" step in the [developer documentation](https://mydata.athenahealth.com/access-the-apis), the sandbox tries to POST the selected patient's access code to my client's redirect URL.  Given that this doesn't line up with my understanding of the [SMART launch sequence](http://www.hl7.org/fhir/smart-app-launch/), why is this happening?

**Any background information about this question**

I'm trying to get the [SMART on FHIR JavaScript Library](https://github.com/smart-on-fhir/client-js) working with the AthenaHealth sandbox.  Currently running my app on localhost; the app already works with the public SMART sandbox.

**Comment by dwwinters** [comment]
I believe I have tracked down the answer to my question.  It was [this response](https://github.com/virencehealth/apiserver.virencehealth.com/issues/7#issuecomment-392872433) in an old issue that explained why the sandbox was trying to POST to my app.  By default this is what the sandbox will do, unless you specify a `response_mode` query parameter, which are detailed in the [OpenID spec](https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#ResponseTypesAndModes).  The [developer documentation for the sandbox](https://mydata.athenahealth.com/access-the-apis) doesn't mention this query parameter, but it is referenced in the above issue as well as in the [example Express application in this repository](https://github.com/virencehealth/apiserver.virencehealth.com/blob/master/token-generation-sample-code/index.html#L50).  The [SMART documentation](http://hl7.org/fhir/smart-app-launch/#smart-authorization-and-resource-retrieval) assumes the authorization code is sent back within the redirect URL as a query parameter and makes no mention of the POST response mode option.

I think what I need to do is just change the `response_mode` to `query` and the sandbox should behave similarly to what is described in the SMART documentation.  However, I can't test this because the sandbox appears to be down (similar error message as was documented in [this issue](https://github.com/virencehealth/apiserver.virencehealth.com/issues/166) earlier this year).

**Comment by Torin-Shepard-athena** [comment]
@dwwinters Have you retested your integration with https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer

**Comment by dwwinters** [comment]
@Torin-Shepard-athena I have retested.  I had to modify my application to handle the non-SMART way the athenahealth API responds to an authorization request.  Am planning on posting back here once I publish my updated application and then I can close this issue.
