### ISSUE TITLE
Access token expire in 60 min, needs to re-generate an authorization code again and again manually.

### ISSUE THREAD

**Issue by ARCSIndia** [athenahealth/apiserver-athenaFlex#173]
Hello,

I am able to access API, but once Access Token expire, Needs to e-generate an authorization code again and again manually?

The authorization code through exception when sending message on Re-Generation of token using same authorization code
"error_description": "User session not found. User must re-authenticate."

On every 60 minutes I manually generate an authorization code after Construct the Access My Data URL.

Thanks,
Pankaj

**Comment by AjeetYadav07** [comment]
The access token will expire in 60 min as per design. If you don't want to generate authorization code again and again, then create a refresh token so that you can create a new access token from this refresh token. Please look at Github #167 to create a refresh token.

**Comment by ARCSIndia** [comment]
I also reverted on  [#167](https://github.com/virencehealth/apiserver.virencehealth.com/issues/167), I tried but only get access_token, not received Refresh_token.
![Token_Response](https://user-images.githubusercontent.com/52694390/109329272-632d6b00-7880-11eb-9c3a-7178884fc314.png)

**Comment by AjeetYadav07** [comment]
Please check the access my data url. Construct the url with offline_access like below:

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.*%20launch/patient%20offline_access&response_type=code%20id_token&redirect_uri={REDIRECT_URL}&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id={CLIENT_ID}

**Comment by ARCSIndia** [comment]
Thanks you @AjeetYadav07 , this work for me.

**Comment by ARCSIndia** [comment]
Able to generate Refresh_token & then using this token get a new Access_token. This work on continuous API hits. 

On my case I have to process my application once in a day, It run and call some API, collect Data & stop. It will take 1-2 hours process. Where Refresh token will generate a new token. both expire timeout after 60 min.

Next day application reprocess the same, that time both token Expire with error:
"error_description": "Refresh token could not be mapped to the original authorization request. User must re-authenticate."
Again we reached to manually generate the code.

**Comment by ARCSIndia** [comment]
@AjeetYadav07 Now I am unable to generate Auth Code using the same URL:
https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.*%20launch/patient%20offline_access&response_type=code%20id_token&redirect_uri={REDIRECT_URL}&aud=https%3A%2F%2Fcpsapisandbox.virenceaz.com%3A9443%2FdemoAPIServer&client_id={CLIENT_ID}

[Code_Request.txt](https://github.com/virencehealth/apiserver.virencehealth.com/files/6090439/Code_Request.txt)
[Code_Response.txt](https://github.com/virencehealth/apiserver.virencehealth.com/files/6090440/Code_Response.txt)
![image](https://user-images.githubusercontent.com/52694390/110115159-b69d3d00-7ddb-11eb-8eec-babdb3949d59.png)

**Comment by AjeetYadav07** [comment]
Please try with new URL with the new DNS name without the port number for sandbox.
Instead of https://cpsapisandbox.virenceaz.com:9443/demoAPIServer use https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer.

**Comment by ARCSIndia** [comment]
> Please try new URL with the new DNS name without the port number for sandbox.
> Instead of https://cpsapisandbox.virenceaz.com:9443/demoAPIServer use https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer.

Please also suggest to solve this
https://github.com/athenahealth/apiserver-athenaFlex/issues/173#issuecomment-787675682

**Comment by ARCSIndia** [comment]
> @AjeetYadav07 I able to generate Refresh_token & then using this token get a new Access_token. This work on continuous API hits.
> 
> On my case I have to schedule my application once in a day on server, It run and call some API, collect Data & stop. It will take 1-3 hours process. Where Refresh token will generate a new token.
> 
> Next day application reprocess the same, that time both token Expire with error because both expire timeout after 60 min.
> "error_description": "Refresh token could not be mapped to the original authorization request. User must re-authenticate."
> Again we reached to manually generate the code.

@AjeetYadav07  Please suggest, how I automate this Token Generation process? 
I am still waiting for your valuable revert.

**Comment by ARCSIndia** [comment]
@Torin-Shepard-athena @AjeetYadav07 Please suggest, how I automate this Token Generation process?

**Comment by Torin-Shepard-athena** [comment]
As mentioned in #107, the CPS 12.3 product has a known issue where refresh tokens expired too soon. This issue has been fixed in athenaPractice V20

You should be able to use a stored refresh token to get a new access token.  Refresh tokens are valid for 90 days.  When the refresh token expires, you will need to get start a new refresh token cycle by getting a new auth code and exchange it for new access token and refresh token.

Please test your application with https://apsandbox.fhirapi.athenahealth.com/demoAPIServer.

**Comment by AjeetYadav07** [comment]
Closing this issue. if you have any further query please raise a new ticket.

**Comment by ARCSIndia** [comment]
> As mentioned in #107, the CPS 12.3 product has a known issue where refresh tokens expired too soon. This issue has been fixed in athenaPractice V20
> 
> You should be able to use a stored refresh token to get a new access token. Refresh tokens are valid for 90 days. When the refresh token expires, you will need to get start a new refresh token cycle by getting a new auth code and exchange it for new access token and refresh token.
> 
> Please test your application with https://apsandbox.fhirapi.athenahealth.com/demoAPIServer.

Using following  server : https://apsandbox.fhirapi.athenahealth.com/demoAPIServer.
Now getting Error
![auth-callback-error](https://user-images.githubusercontent.com/52694390/121183926-3545c280-c882-11eb-9d20-48f792efbcc7.png)

I am able to get Auth code using https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer/
