### ISSUE TITLE
Is there is Billing/Invoice API End Points & provide valid Ids to get Appointment Records.

### ISSUE THREAD

**Issue by ARCSIndia** [athenahealth/apiserver-athenaFlex#175]
Documentation have Billing/Invoice API End Points. please suggest which one is?

Also Please provide an Patient/Location/Practitioner Id for I can get appointment records. I tried with multiple Patient/Location/Practitioner, but the response is same as "total": 0,
{
"resourceType": "Bundle",
"id": "1.2.840.113619.21.1.8899560752578716278.10.1614580669844.131229",
"meta": {
"lastUpdated": "2021-03-01T06:37:49.844Z"
},
"type": "searchset",
"total": 0,
"link": [
{
"relation": "self",
"url": "https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Appointment?_format=json&patient=1902008249235680"
}
]
}

**Comment by AjeetYadav07** [comment]
Appointment without any search parameters will return OperationOutcome indicating Appointment resource requires location parameter to be able to search across patients. The location ids can be discovered by querying Location resource.

Location resource can be searched across patients without any search parameters.
Location?_count=50

Extract location ids with prefix “FAC-“ for facilities.

Query Appointment by a list of facilities
Appointment?location=FAC-403,FAC-404,FAC-405,FAC-406. Please look at github issue #140 and #136

Supported resources are listed here at https://mydata.athenahealth.com/fhirapidoc
