### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by soneal-relatient** [athenahealth/apiserver-athenaFlex#178]
We are experiencing a permission denied error response when trying to authenticate against the new sandbox URL using the **client_credentials** authorization grant type.

### Response

```json
{
  "error": "unauthorized_client",
  "error_description": "Permission Denied"
}
```

### Request

```bash
curl "https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/token?grant_type=client_credentials&scope=user%2F*.*" -H "authorization: Basic aHdpbnN0b25Ac2JveHByb3Z0ZW5hbnQuY29tOlRlc3RQcm92aWRlciFA" --data '{}' -X GET
```

**Comment by Torin-Shepard-athena** [comment]
Please try again.  There may have been some temporary issues during the process of making configuration changes to enable the new URL with the new DNS name without the port number.

**Comment by AjeetYadav07** [comment]
Closing this issue , if you have any Query please raise a new ticket.
