### ISSUE TITLE
How to handle patients marked "Sensitive"?

### ISSUE THREAD

**Issue by mikeseale** [athenahealth/apiserver-athenaFlex#179]
When a patient is marked sensitive in the EMR, the FHIR API doesn't show any data in the requests.  Usually, this is done to keep others from viewing the chart for various reasons; however, it shouldn't keep the patient from viewing their own data.  What would be the process for the patient to view their data via the FHIR API if their chart is marked sensitive in the EMR?

**Comment by Torin-Shepard-athena** [comment]
A special "Patient" user exists as part of Patient API Access features. This makes it possible for the FHIR API Server to enforce access controls in a consistent manner between patients and users.

All patients will use the same single “Patient” user account, and thus will all have the same permissions.  If any given B2C AAD person identity has been authorized access to a patient record through an email address, that person should have access to the entire patient record.  This means the “Patient” user must have sufficient security permissions for the FHIR API Server allow access.

Grant view sensitive charts and view sensitive registration permissions to the “Patient" user.

**Comment by mikeseale** [comment]
Is there a way to know which user that is?  We have a user named Patient API, but I have given it view sensitive chart permission.  It still seems to be an empty FHIR request after that change.  (CPS v12.3)

**Comment by Torin-Shepard-athena** [comment]
When permissions are changed, they are not reflected in existing access tokens which are valid for 1 hour duration.  User permissions are determined before access tokens are issued.  New user permissions be reflected in only access tokens issued after the permission changes.

**Comment by GaryHammer701** [comment]
Is this request coming from a third-party API or from the traditional kind of patient portal such as one from Surescripts?

**Comment by mikeseale** [comment]
It's been a few day since I made the security change, but we are still getting an empty request when our test patient is marked sensitive in registration.  I went to take a look at the logs to see what information could be gleamed to troubleshoot.

`TAU732D06: User permissions for Patient granted in CPS/EMR are [PERMISSION_VIEW_ATTACHMENT_-_PATIENT, PERMISSION_CHART, PERMISSION_VIEW_SENSITIVE_CHARTS, ROLE_AUTHENTICATED_USERS, PERMISSION_VIEW_FINANCIAL_-_PATIENT, PERMISSION_REGISTRATION, PERMISSION_VIEW_CHARTS, PERMISSION_SCHEDULE]`

That log is followed up by what seems to be the query that is used to get the patient details on our first API call, which seems to filter out any patient marked sensitive.  Sensitive patients have a 1 in the column SensitiveChart.  1875864535440490 is the test patient PID.

`SELECT TOP 20  V.* FROM FHIR_PATIENTVIEW V WHERE ( V.PID = '1875864535440490' )  AND (V.SENSITIVECHART = 0 OR V.SENSITIVECHART IS NULL) AND (V.PID NOT IN (1592470698001020)) AND (V.PID = 1875864535440490 ) ORDER BY V.PID DESC `

@GaryHammer701 
More of a traditional kind of patient portal.  We are creating the patient portal on top of FHIR and a custom API for outlier tasks that aren't currently implemented with Centricity's FHIR.

**Comment by Torin-Shepard-athena** [comment]
This may be a known issue with authorization flow in the CPS 12.3.  The issue is fixed in athenaPractice V20.

@mikeseale
Can you please test your application with https://apsandbox.fhirapi.athenahealth.com/demoAPIServer?  Test patient Cindy Stafford is marked as sensitive in this system.

https://mydata.athenahealth.com/access-the-apis gives the sample personal account credentials for patient workflow to authenticate as athenainterop@aol.com.  This email is authorized to access Cindy Stafford's patient record.

@GaryHammer701
See JIRA INTROP-2236 = ADO Bug 53194

**Comment by GaryHammer701** [comment]
testing with my own account in our support lab, when I remove the view sensitive chart permission I cannot get CCDAs for sensitive patients and when I add it back, I can get those when I request new tokens.  The permissions I see in the FHIR debug log match those in this SQL query:
select * from FHIR_SECURITYAUTHVIEW
where username = 'Patient'
and authority like '%SENSITIVE%'
order by 2

**Comment by mikeseale** [comment]
I have confirmed that in v20 sensitive patients have data returned from the FHIR API.
