### ISSUE TITLE
Error when attempting to register an App

### ISSUE THREAD

**Issue by healthbanksdev** [athenahealth/apiserver-athenaFlex#181]
While creating Application I am receiving the following error:
"Registration Failure
Your registration was unsuccessful"

We are a software company from the Boston area with a formerly approved and running Centricity API integration.  However we haven't had a Centricity customer since Centricity became Virence (and now Athena) so I haven't needed to use our integration.  Now we have several Centricity clinics wanting our products so I'm wanting to re-establish the integration.  I see since we do not have any "Apps" in your Dev portal so I'm concerned that we need to start the approval process all over again.  I tried registering an App but received the error above.

Please advise.

**Comment by Torin-Shepard-athena** [comment]
@healthbanksdev 
Meeting with HealthBanks and athenahealth took place June 4, 2021.  During this meeting app registration was successful.  Closing this issue as not reproducible.
