### ISSUE TITLE
Issue: Client ID is required in the Authorization header for confidential apps and as a query parameter for public apps

### ISSUE THREAD

**Issue by ARCSIndia** [athenahealth/apiserver-athenaFlex#182]
As mentioned in #173 , Please test your application with https://apsandbox.fhirapi.athenahealth.com/demoAPIServer.

Using same Base Url able to generate Auth Code but Now getting new error after updated the provided base Url to Token generation code using Authorization code. I used the Client Id as per Error on Header.
[24-05-2021 Request Response.zip](https://github.com/athenahealth/apiserver-athenaFlex/files/6530209/24-05-2021.Request.Response.zip)

Client ID is required in the Authorization header for confidential apps and as a query parameter for public apps

Please suggest the changes I have to do with the Base URL changes.

**Comment by ARCSIndia** [comment]
@AjeetYadav07 @Torin-Shepard-athena Please address it.

**Comment by Torin-Shepard-athena** [comment]
@ARCSIndia The Postman request you uploaded shows your POST request to the token endpoint is is using Bearer authorization type.  This is not supported. Please change to use Basic Auth.

Change FROM:
request.AddHeader("Authorization", "Bearer Base64EncodedClientID:ClientSecret");

Change TO:
request.AddHeader("Authorization", "**Basic** Base64EncodedClientID:ClientSecret");

Please see the screenshot of the using Postman to make the POST token request at our Developer Portal under "Generate and access token" at at [API Access](https://mydata.athenahealth.com/access-the-apis).
![image](https://user-images.githubusercontent.com/52474202/119579482-4fa47a00-bd73-11eb-9ad2-ba38acecc5c8.png)

4. Select the Authorization tab then enter the following into the Authorization screen:
a. Select **Basic Auth** from the **Type** drop-down field.

**Comment by ARCSIndia** [comment]
@Torin-Shepard-athena I follow the URL: https://mydata.athenahealth.com/access-the-apis
[26-05-2021 Request Response.zip](https://github.com/athenahealth/apiserver-athenaFlex/files/6544918/26-05-2021.Request.Response.zip)

Using Basic Auth as Authorization Header Getting Issue on generate token.

I tried multiple time to generate Access token. Taken less than one minute but always say "User session not found. User must re-authenticate." (Enclosed Postman Request Response).
Please Take a look: https://www.loom.com/share/735eadd9f63e4c46ac0a1159df893639

{
    "expires_in": 0,
    "error": "invalid_client",
    "error_description": "User session not found. User must re-authenticate."
}


Authentication failed using authorization_code captured from URL:
https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.*%20launch/patient%20offline_access&response_type=code%20id_token&redirect_uri=https://portal.redspotinteractive.com&aud=https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL3d3dy5jZW50cmljaXR5dXNlcnMuY29tXC8iLCJncmFudF90eXBlcyI6WyJhdXRob3JpemF0aW9uX2NvZGUiXSwiaXNzIjoiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tIiwicmVkaXJlY3RfdXJpcyI6WyJodHRwczpcL1wvcG9ydGFsLnJlZHNwb3RpbnRlcmFjdGl2ZS5jb20iXSwidG9rZW5fZW5kcG9pbnRfYXV0aF9tZXRob2QiOiJjbGllbnRfc2VjcmV0X2Jhc2ljIiwic29mdHdhcmVfaWQiOiIxLjAuMCIsIm5hdGl2ZV9jbGllbnQiOmZhbHNlLCJodHRwczpcL1wvbXlkYXRhLmdlaGVhbHRoY2FyZS5jb21cL29hdXRoMi5jbGFpbXNcL2FwcF9pZCI6ImNkY2Y4MzkxLTU5ZGItNGNmMy04ZTZkLTk4OWFhODFmYTRjOCIsImV4cCI6MTkyODMxODcyNiwiY2xpZW50X25hbWUiOiJSZWRzcG90SW50ZXJhY3RpdmUiLCJpYXQiOjE2MTI3ODU5MjYsImNvbnRhY3RzIjpbImFqYWluQHJlZHNwb3RpbnRlcmFjdGl2ZS5jb20iXSwicmVzcG9uc2VfdHlwZXMiOlsiY29kZSJdfQ.XfFIROARu-hkRmhRoloMowCrx0EetuKVKhMyGWP_Hq_utfyN4KZ1MYYbt8Gan1-Mydc--aGPF1jhnNGbsPQLEDxiHjbwKO-VIXUHFUs0U10k7vq2xHLi4EKmBXNtdpj4gu2lHyRdKsSIPpjpM3Ufv1NCgiywTQ16Y0nyNr54-MU

**Comment by Torin-Shepard-athena** [comment]
@ARCSIndia I think you may not have realized you attempted to use different FHIR Servers.
You got authorization code from authorize endpoint of one FHIR Server and presented it the token endpoint of a different FHIR Server.  This is not supported. You cannot mix and match security objects between different FHIR Servers (for obvious reasons).

We have 2 API Sandbox FHIR Servers.
CPS 12.3 **cpsapisandbox**.fhirapi.athenhealth.com
athenaPractice v20 **apsandbox**.fhirapi.athenahealth.com.

Please try using both authorize and token endpoints from the v20 machine.
