### ISSUE TITLE
Not all appointments found when paging via the _count filter

### ISSUE THREAD

**Issue by healthbanksdev** [athenahealth/apiserver-athenaFlex#185]
There are 2 appointments in the date range given by this url:
https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Appointment?_format=json&date=ge2012-01-01T00:00:00.000Z&date=le2021-05-27T00:00:00.000Z&location=FAC-3

However, if using the _count parameter to page through the records one at a time the 2nd appointment is not found.
eg. 
Page 1 (correctly shows the first appointment):
https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Appointment?_format=json&_count=1&date=ge2012-01-01T00:00:00.000Z&date=le2021-05-27T00:00:00.000Z&location=FAC-3

Then, using the Next element given on page 1 to get the next page does not show any appointments:
https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Appointment?_after=253&_count=1&_format=json&date=ge2012-01-01T00%3A00%3A00.000Z&date=le2021-05-27T00%3A00%3A00.000Z&location=FAC-3

**Comment by AjeetYadav07** [comment]
@healthbanksdev
Thanks for making us aware for the issue .It is under investigation to determine the required solution..
