### ISSUE TITLE
Appointment endpoint:  include patient data?

### ISSUE THREAD

**Issue by healthbanksdev** [athenahealth/apiserver-athenaFlex#186]
Hi, is it possible to include patient data in the Appointment result-set?

eg: This returns 7 appointments:

https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Appointment?_format=json&_count=200&date=ge2000-05-27T00:00:00.000Z&date=le2022-05-27T23:59:59.000Z&location=FAC-3&status=cancelled

To get the patient details for the appointments I'm currently calling the Patient endpoint for each of the 7 appointments.  Is there any way to have the patient data included in the Appointment result-set?

**Comment by Torin-Shepard-athena** [comment]
@healthbanksdev
Our API Servers have some support for FHIR _include searches.
Add this parameter to your FHIR queries for Appointment resources: &_include=Appointment:patient
Our Appointment API supports the following includes.
Appointment:*
Appointment:actor
Appointment:location
Appointment:patient
Appointment:practitioner
