### ISSUE TITLE
Patient Login Redirects to Invalid URL

### ISSUE THREAD

**Issue by Haribou** [athenahealth/apiserver-athenaFlex#187]
When implementing the steps described in https://mydata.athenahealth.com/access-the-apis for a patient-facing login, I arrive at a URL such as this one: https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?aud=https%3A%2F%2Fcpsapisandbox.fhirapi.athenahealth.com%3A443%2FdemoAPIServer&response_type=code%20id_token&client_id=[my client ID]&redirect_uri=[my redirect URI]&state=defaultState&scope=openid%20profile%20patient%2F*.read%20launch%2Fpatient. When I plug this URL into a Chrome browser, the Athena server presents me with a personal account and work account page. If I click the personal account option, the browser redirects to https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize-callback, which results in "This site can’t be reached cpsapisandbox.virenceaz.com refused to connect."

Any ideas how to overcome this showstopper issue? Is there something wrong with my URL?

![personalAccount](https://user-images.githubusercontent.com/33349961/122680536-9f813000-d1bd-11eb-8f47-db1689a81182.PNG)

![error](https://user-images.githubusercontent.com/33349961/122680538-a019c680-d1bd-11eb-8bee-07e48050e906.png)

**Comment by Torin-Shepard-athena** [comment]
@Haribou Sorry for the delayed response.  Thank you for notifying us.  Our Cloud Ops team has been notified to make a configuration change that was missed when the domain name was changed in the transition from Virence to athena.

As noted on the readme on the main page of this GitHub forum, we also have athenaPractice V20 API Sandbox FHIR Server apsandbox.fhirapi.athenahealth.com.  Can you please uses it to test patient API access before the configuration issue is resolved on cpsapisandbox.fhirapi.athenahealth.com?

**Comment by Torin-Shepard-athena** [comment]
@Haribou
The personal account login for patient workflow is now working properly again on cpsapisandbox.fhirapi.athenahealth.com.

**Comment by Torin-Shepard-athena** [comment]
Patient API Access with the published sample patient credentials is working as expected for both cpsapisandbox.fhirapi.athenahealth.com and apsandbox.fhirapi.athenahealth.com
