### ISSUE TITLE
Your session timed out or the authorization request was invalid.

### ISSUE THREAD

**Issue by ARCSIndia** [athenahealth/apiserver-athenaFlex#188]
As mentioned in #173 
Using following server : https://apsandbox.fhirapi.athenahealth.com/demoAPIServer.
Now getting Error
![auth-callback-error](https://user-images.githubusercontent.com/52694390/121184702-fa905a00-c882-11eb-823a-e19842155073.png)

I am able to get Auth code using but in this token expire in 60 min https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer/

Please suggest to overcome this issue using https://apsandbox.fhirapi.athenahealth.com/demoAPIServer.

**Comment by AjeetYadav07** [comment]
@ARCSIndia 
apsandbox working as expected, try the below access my data url:
 https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=[{REDIRECT-URL}]&aud=https%3A%2F%2Fapsandbox.fhirapi.athenahealth.com%2FdemoAPIServer&client_id=[{CLIENT-ID}]
