### ISSUE TITLE
Is there a timeout/cleanup of the Apps in Dev Center?

### ISSUE THREAD

**Issue by AOCjcarr** [athenahealth/apiserver-athenaFlex#189]
About 3 months ago we created an app in the Dev Center and were able to pull the client ID and client secret.
This project  has been on hold for a few months and has not been used.   To our surprise we logged into the Dev Center today and it is showing no Applications exist yet for us (tried two different user accounts that would it could have been created under)

Curious if because the app had not been used if it gets automatically cleaned up or if something else may have occurred that removed it from the application list.

Believe the app name was "AllianceChicago eCRNow"   and we do have the clientID and secret, but did not save the entries used when creating the app.

Just want to make sure before we look into just re-registering the app as we prepare to move forward with integrating soon
Thanks
Jeremy Carr

**Comment by AjeetYadav07** [comment]
@AOCjcarr
We do not have any timeout or cleanup of apps in Dev Portal. Please re-register the application.

**Comment by Torin-Shepard-athena** [comment]
Closing this issue.  Alliance has been successful in using athenaPractice with eCR Now modified to use authorization flow described in #177.
