### ISSUE TITLE
Appointment Status Missing

### ISSUE THREAD

**Issue by nmo-dev** [athenahealth/apiserver-athenaFlex#190]
I am currently in our production environment trying to do an appointment "GET" call. However, I am experiencing a problem with getting the status of the appointment in CPS (v20.1). Sometimes the status is there as "pending", other times it's missing all together (usually when the appointment is canceled). The call I'm performing is:

<server>/fhir/Appointment/<appointment_id>

The call is successful but is missing that particular data. I am trying to reliably get the appointment status (booked, pending, canceled, etc.) from CPS. Was hoping to get some insight on why this particular behavior is happening.

Thanks.

**Comment by Torin-Shepard-athena** [comment]
@nmo-dev
FHIR Appointment status mappings must match Appointment Cancel and Status values defined in Administration module.

Appointment status mappings are stored in a configuration file on the Interop Server.
C:\Program Files\Centricity Practice Solution\jboss\standalone\deployments\dbnameAPIServer.war\WEB-INF\classes\com\gehcit\fhir\mappers\util\mappings.properties
APPOINTMENTSTATUS_CPS entries in this file must be edited if any changes are made to the default appointment status values and if customers define their own appointment status values in athenaFlow Administration module.

If the appointment status entries are correct in mappings.properties file, the absence of Appointment.status element can be interpreted as Appointment.status having value pending.

![image](https://user-images.githubusercontent.com/52474202/125341377-647ba380-e308-11eb-8364-75ef69accd4b.png)

**Comment by nmo-dev** [comment]
That worked. Thank you for this.
