### ISSUE TITLE
can not get encounter id from token

### ISSUE THREAD

**Issue by nutionMedivn** [athenahealth/apiserver-athenaFlex#192]
I am using the sandbox for testing. sandbox url is 'https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir'.

According to the documentation (https://mydata.athenahealth.com/access-the-apis),  I login in Work account using 'hwinston@sboxprovtenant.com'.

But I can not get encounter id from token after choosing patient.

Is there a place to configure or choose Encounter. The sandbox do not support create or update operations for Encounter.
![image](https://user-images.githubusercontent.com/31340946/126301430-c069afd9-9fd2-45a3-ab69-12b92439f229.png)

**Comment by Torin-Shepard-athena** [comment]
@nutionMedivn Please give more information about the create and update interactions you want to perform with our FHIR APIs.

https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/metadata
The Conformance statement indicates which resource types support create and update interactions.

Creates and updates to clinical resource types Condition, Immunization, MedicationStatement, Observation will automatically create a new on-hold API Update document in athenaPractice/athenaFlow if necessary or associate the clinical item creates/updates with an existing API Update document (Encounter) in athenaPractice.
