### ISSUE TITLE
Posting back into athenaPractice

### ISSUE THREAD

**Issue by BYUSHC** [athenahealth/apiserver-athenaFlex#196]
Where is the documentation to POST back into athenaPractice?  I don't see this on the Developer portal.

I'm trying to send appointment information.

**Comment by Torin-Shepard-athena** [comment]
@BYUSHC
We are aware more information could be added to the API documentation for FHIR writes.  Although the supported interactions and operations are listed, we recognize some people want more details and samples of requests for creating/updating writable resource types.

Remember you can search this GitHub forum for previous postings from other developers with similar questions.

Issues #21, #108, #165 have sample request payloads for creating appointments.
