### ISSUE TITLE
POST  Observation example

### ISSUE THREAD

**Issue by AOCjcarr** [athenahealth/apiserver-athenaFlex#197]
We are working with a vendor on a research CDS feasibility study that needs to include a POST of Observation back to athenaPractice for several specific obsterms/HDID.

Does anyone have a sample functioning Observation Post statement that we can use as a template to start our statement with, specifically to note the required fields and Syntax to post back into the open encounter where we started the call.  

I believe if we have a example of a working POST statement we can evaluate that to make the necessary changes to develop the post statements for the observations that we are looking to populate.

Any help would be greatly appreciated as we have found the portal API Resource document while very comprehensive is lacking code examples of both GET and POST statements that are helpful to understand how the calls should be structured properly.

Thanks!
Jeremy Carr
AllianceChicago

**Comment by AOCjcarr** [comment]
Additional question/clarifications that would be great to see in an example.  We are looking to post multiple observations to the existing document that we are calling the API from.  We will pass them the SDID to be returned as the encounter in the post, but what is the proper formatting to include the group of multiple observations to be posted back to the active encounter in AP as well as any other required fields that must be indicated in the POST statement to allow the post back to AP.
We are attempting a very basic statement right now and that is hitting a 403 - Unauthorized  error, using the same API account that is able to do a GET of the observations.

**Comment by Torin-Shepard-athena** [comment]
Posting this sample Bundle will create a new unsigned API Update document.
[Sample_FHIR_OBS_Write_Bundle.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/6964920/Sample_FHIR_OBS_Write_Bundle.txt)

Subsequent posts should add more OBS to the same API Update document if it has not yet been signed.

The security permission/privilege named 'API Writes' is used to control which users are authorized to perform clinical writes.
Grant permission in athenaPractice UI
Administrator > User and Resource Management > User Management > Select User > Security > API Writes

Grant permission in athenaFlow UI
Go > Priviliges > Select User > Setup > API Writes

See also #69 and #71

**Comment by AOCjcarr** [comment]
Thank you Torin-

This will be helpful especially around the bundling and security, I had missed that the new permission was added.
Thanks for the example!  I am seeing the value, patient, and practitioner, does it not need a date, or is that assume the document clinical date if not defined?

As far as the encounter, our scenario is a bit different as the API is part of an active visit to trigger, process and post back the results..     We will be triggering the API CDS call from our clinical content, which will then do a FHIR GET  call to aP to gather information, and ultimately a POST call back to aP that we need to post the results to the same encounter we launched from so that the result Observations can be tied to the document as well as included in the visit summary.

The trigger to the external API is through a button in the our aP content that generates a POST call to the FHIR API (hosted within our network) and pass within the post to the API application variables that include the PID, SDID, and Provider of the active document where the call was made.    The plan is to utilize these variables to post the Observations back to the same encounter in aP.
Can we do so by assigning the SDID that is provided to the API back in the POST statement  (Document will still be in process as user should be actively working in it while the CDS processes)



Thanks,
Jeremy Carr

CELL 773.580.0099
***@***.******@***.***>

**Comment by AOCjcarr** [comment]
@Torin-Shepard-athena  any additional insight on the follow up questions?  We have a 2 hour meeting with the vendor on Thursday afternoon and hoping to make some progress to meet this goal on functionality that needs to be rolled out by the end of the month
Not sure if you may even be available 12-2 PST Thursday to assist if you can as we are attempting to build a test Observation POST statement via postman, which once successful, the vendor (will also be on the call) will integrate that format into their code that would make the actual code.

**Comment by Torin-Shepard-athena** [comment]
@AOCjcarr All FHIR clinical writes are done using "API Update" document type.

If unsigned API Update document does not exist, a new one is created when FHIR POST request is used to write clinical items.  If unsigned API document exists, FHIR POST and PUT requests to write clinical items will associate the new/modified items with the existing API Update document.  These documents are put on hold after FHIR POST/PUT request completes.

After considerable discussion with many stakeholders, a decision was made that FHIR APIs should not support adding clinical items to any other document type to avoid the complexities/issues that might happen if we were to allow FHIR APIs to create/update clinical items in documents being modified using athenaPractice/athenaFlow client applications.  Part of this decision was influenced by the fact that some FHIR apps are designed for patients and feedback from most customers told us that any updates from patients should always be put in separate unsigned documents for clinicians to review before incorporating the changes into the Chart.

After an API Update document is signed, a visit summary can be generated for it separately.  We will need to schedule time to talk about the feasibility of future enhancements to consider the workflow you suggest where an encounter form can launch a SMART on FHIR app which would like to write clinical items into the same active encounter.

**Comment by AOCjcarr** [comment]
Thanks Torin!
We will be reviewing this with the team to assess how this impacts the scoped design for the research projects and expected deliveries

Thanks,
Jeremy Carr

CELL 773.580.0099
***@***.******@***.***>

**Comment by AjeetYadav07** [comment]
Marking this issue as closed. Please reopen if you still face any issues.

**Comment by AOCrpunzalan** [comment]
> 

@Torin-Shepard-athena  - 

> @AOCjcarr All FHIR clinical writes are done using "API Update" document type.
> 
> If unsigned API Update document does not exist, a new one is created when FHIR POST request is used to write clinical items. If unsigned API document exists, FHIR POST and PUT requests to write clinical items will associate the new/modified items with the existing API Update document. These documents are put on hold after FHIR POST/PUT request completes.
> 
> After considerable discussion with many stakeholders, a decision was made that FHIR APIs should not support adding clinical items to any other document type to avoid the complexities/issues that might happen if we were to allow FHIR APIs to create/update clinical items in documents being modified using athenaPractice/athenaFlow client applications. Part of this decision was influenced by the fact that some FHIR apps are designed for patients and feedback from most customers told us that any updates from patients should always be put in separate unsigned documents for clinicians to review before incorporating the changes into the Chart.
> 
> After an API Update document is signed, a visit summary can be generated for it separately. We will need to schedule time to talk about the feasibility of future enhancements to consider the workflow you suggest where an encounter form can launch a SMART on FHIR app which would like to write clinical items into the same active encounter.

@Torin-Shepard-athena  - I just wanted to confirm that the above applies to Conditions as well.  We are working on integrating an API that will send a Condition POST request and hoping that it will follow the process you described above.  Also, do you have a sample json request for Condition you can send over?

**Comment by AOCjcarr** [comment]
So to clarify, this is a new scenario being mentioned by Rhein.   Discussion/question above was specific to the API calls within an encounter to update the current document.

New scenario is more along the lines of expected FHIR workflows you mention Torin, with unsolicited posts that are received to post updates to specific charts.   This new project is looking to return and post  a condition and/or observation to the chart along with additional supporting text that will be related to the recommended updates.

@Torin-Shepard-athena    To Rhein's question, looking to validate that Condition/Observations POST will create a document if not already existing as unsigned.     If there are multiple  updates both Condition/Observation will both then post to the same new or already open document?
What happens if the is a API Update already open from previous API activity?  Is there risk that this new update may add into an unsigned APIUpdate from a prior date, or even a different API if it was still pending unsigned?  Or is there anything to ensure updates are from the same API external source or document date?

Is this a consideration that will need to be build into user training to ensure these types of documents are not left unsigned as it could receive updates from other interfaces?

**Comment by Torin-Shepard-athena** [comment]
@AOCjcarr @AOCrpunzalan 
Each API Update document has a source id that comes from information in the access token.  athenaPractice FHIR Server has checks in place to make sure a single source can perform multiple clinical writes in the same API update document.  Different FHIR apps can each have their own separate API Update documents.  With the normal 2-step authorization flow (get auth code and exchange it for access token) the FHIR application name appears as the document summary and the source id is set to the app_id claim embedded in the app's client id.

V20 has a known limitation with the older token GET native user authorization which has only user credentials but not app credentials.  With this flow, the document source id is set the the PVID of the authenticated user.

In V22, this old token GET is deprecated and replaced by a new token POST with grant_type = password that requires both application and user credentials.

I appreciate you commenting about this GitHub issue because it helped me/us realize this new native user authorization mode needs to be updated to use the source app credentials instead of only the user identity.  A bug has been submitted so the new token POST will use use the correct source id. 

I recommend you do not use the old native user auth token GET for FHIR clinical writes because it will prevent the ability to do any data analysis/reporting on documents with clinical data written by multiple FHIR applications.  This could confuse practitioners if clinical data from different workflows and applications is mixed together by only user instead of being separated by application as well.
