### ISSUE TITLE
Unable to generate Access Token ID

### ISSUE THREAD

**Issue by tthai4** [athenahealth/apiserver-athenaFlex#202]
Getting "500 Internal Server Error" (i.e. An unexpected error has occurred.  Please try this operation again later) when generating Access Token Id.  Please advise.  Thank you .

TT

**Comment by Torin-Shepard-athena** [comment]
@tthai4
Please clarify what you mean by the phrase "access token id".  It is not clear why you added the word id after access token.

Are you getting authorization code from authorize endpoint?
Are you getting unexpected error from the token endpoint instead of access token?
Please give more information including full URLs (you may omit your client id/secret) you are using with the authorize and token endpoints.

As mentioned on the https://github.com/athenahealth/apiserver-athenaFlex home page and #166 and #199, the host name has changed.

Use cpsapisandbox.fhirapi.athenahealth.com without any port number instead of cpsapisandbox.virenceaz.com:9443.

As noted on the readme on the main page of this GitHub forum, we also have athenaPractice V20 API Sandbox FHIR Server apsandbox.fhirapi.athenahealth.com

We apologize for any inconvenience and confusion from out of date information on the Access the APIs page.

**Comment by tthai4** [comment]
Hi Torin,

Yes, it should be the access token.  Sorry about that.  Below is the error I was getting when request access token.

***@***.***

**Comment by Torin-Shepard-athena** [comment]
@tthai4
It appears you intended to give a copy of the error you are getting but it was not posted.
We will need to see a copy of the authorize and token requests you are making to help investigate.

**Comment by tthai4** [comment]
Hi Torin,
Yes, that was the error I got this afternoon.  Please give me a few minutes to retry.  Thank you very much.

TT

**Comment by tthai4** [comment]
Torin,

Yes, I have just posted the request.  Thanks.

TT

**Comment by tthai4** [comment]
Torin,

I forgot to paste the authorization code:

0.AS4ABv4ds79inkewavGfnMD99XLq6EX_Wz5CtaIt_CtlH3suAIA.AQABAAIAAAD--DLA3VO7QrddgJg7Wevrb8P_jTuzp_IRei8kpythqeD64H6hI_m8853zRxpnfr7dEjEzz0RIxuoqI8uW4VgoAtIN31fH4ITSLmw6i1Nd1ExCd20jgjswm5kbBV7uyt6Tw2ErDbEhxP6i7VmUp7Kwpdr-psEaf4IrBaw5fgtNWffvMNtRyWbA9UbPR6C5WtOJtw50sr6YpP92FTrrhtFTmcPBrE1D1Q9922tBku0vNLz34d5Z2VpSpuoUkHYwnGzDceTefeN0sOr-QjF1NH_BvSSb1PX_mXbwucgPWEbAdCv_Do1H9e5r6ZU_Cs-QY4crQQYRd_KS7GshrAJ0FybCEDwI7N4dyFgNcqCbL424kAhl3j_phyNGjECj-MEn5_0275i-fBO9Iqpt3jqxYqji2jn7yEm-lTKn3OCdn0vqGkL3mZTIUQTTUw56FJ9FF9SBz9sZJXcts1y63ENBrEygWUTCJMP_Zyj967FfCcJvzjj0M2Xk2uhjIKGXEcQrSifq9bB1QG4XJjmH3FMwC7pepQjjchjsYmGjsZT1rP6yP2-YwYQvp0hHz5T5vYiFNis0AEHsz6WeG79DLSEC-u6TK5zwDxEkQ1PmnGHUojFSYKsjEmd2zGLMAA54ldNueH8G76I-zntFFoZ1iIRb4ccCOCDgZZGCx_gv4X2byixNTSAA~~12425edde7207a08ab0d0b640c928ebba0754e8c1418c93f5bcd5a77ad03d25c679ce27b1a1c5857c43d39e2b393384d0d75613e2561f9bdf119e3546d98efee

**Comment by Torin-Shepard-athena** [comment]
@tthai4 I am sorry.  Even though you state you posted the request, I still do not see a copy of your authorize or token URLs put into the comments here on this GitHub forum.  We need to see the full URLs you are using for both of these endpoints to be able to determine what might be the cause of the behavior you are seeing.

**Comment by tthai4** [comment]
Torin,

Is this the URL you were referring to?

https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/token


Best,
Tien Thai

**Comment by Torin-Shepard-athena** [comment]
@tthai4 I took your authorize URL and changed values for redirect_uri and client_id parameters to match my application registered at the Dev Portal.  I am able to get access tokens successfully for both the sample personal (patient) and work (provider) accounts.

Please confirm you are using your client id and client secret as username and password for Basic Auth in the POST request to the token endpoint.

If possible, upload/attach screenshot or other files with details about the authorization header (you can mask your client secret), key-value pairs in request body, and response you are getting back from token endpoint.  Note: Seeing your auth code does not help determine the cause of the behavior because auth codes are opaque, 1-time use objects.

**Comment by tthai4** [comment]
Torin,

Please see my comment in green below.  Thanks.

Best,
Tien Thai

**Comment by Torin-Shepard-athena** [comment]
@tthai4 Please use github directly to post your comments.  Important information is not getting uploaded to github with the process you are using,  Although you say see comment in green and see screenshot, the comment in GitHub does not have any green text and it does not contain any screenshot.  The email received from notifications@github.com also does not contain any of the information you may be attempting to share.

**Comment by tthai4** [comment]
![Authorization](https://user-images.githubusercontent.com/57362692/129956958-a2cb9f4a-6350-4103-aa32-e0c8e8042f80.jpg)
![BodyandResponse](https://user-images.githubusercontent.com/57362692/129956962-a96e3d29-beb0-470d-a553-394108864ac8.jpg)

**Comment by Torin-Shepard-athena** [comment]
@tthai4 Please try using https://apsandbox.fhirapi.athenahealth.com/demoAPIServer to see if you can get access tokens.
apsandbox has athenaPractice V20
cpsapisandbox has athenaPractice 12.3
It may be necessary for us to restart the machine with the older version.

**Comment by tthai4** [comment]
Torin,
I replaced the Access My Data URL with the one you provided (See below)
**https://apsandbox.fhirapi.athenahealth.com/demoAPIServer**/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=https://dev-aspire.partners.org&aud=**https%3A%2F%2Fapsandbox.fhirapi.athenahealth.com%2FdemoAPIServer**&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL2Rldi1hc3BpcmUucGFydG5lcnMub3JnIiwiZ3JhbnRfdHlwZXMiOlsiYXV0aG9yaXphdGlvbl9jb2RlIl0sImlzcyI6Imh0dHBzOlwvXC9teWRhdGEuZ2VoZWFsdGhjYXJlLmNvbSIsInJlZGlyZWN0X3VyaXMiOlsiaHR0cHM6XC9cL2Rldi1hc3BpcmUucGFydG5lcnMub3JnIl0sInRva2VuX2VuZHBvaW50X2F1dGhfbWV0aG9kIjoiY2xpZW50X3NlY3JldF9iYXNpYyIsInNvZnR3YXJlX2lkIjoiMS4wLjAiLCJuYXRpdmVfY2xpZW50IjpmYWxzZSwiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tXC9vYXV0aDIuY2xhaW1zXC9hcHBfaWQiOiIxY2FkZDU4NC1lMTgzLTQ1MWItYjRiMS0zMmI5ZWY4ODAxNzgiLCJleHAiOjE5NDQ2NjM0NTgsImNsaWVudF9uYW1lIjoiQXNwaXJlQXBwIiwiaWF0IjoxNjI5MTMwNjU4LCJjb250YWN0cyI6WyJ0dGhhaTRAYndoLmhhcnZhcmQuZWR1Il0sInJlc3BvbnNlX3R5cGVzIjpbImNvZGUiXX0.oVwlFk6JUzWRFKQ19uquJx3R-FIp4XcXmFseYGzteNuRYYLzp3_omE0n9N-in1i8he9s9cWoOfMiaEdybnvc7Ek8Tbm9qtM2harzhQabFJLnye6hKggNskspd9mZNh4O53ZIFz-9HDt7srQ8Vxkm8-n6y5Dje5XlFNY83Wtsyvg

I have also replaced the access token URL with the one you provided and sent the request again but still got the same error

![BodyandResponse](https://user-images.githubusercontent.com/57362692/129959760-90e51e9e-bf48-42ca-b34b-c014943106fb.jpg)

**Comment by Torin-Shepard-athena** [comment]
When you see user type selection page, are you choosing work account and entering hwinston@sboxprovtenant sample provider login credentials?
Are you prompted to search for and select a patient after you authenticate sample provider login credentials?
What patient are you selecting?


It appears you may have incorrect scope parameter.  This may not contribute to the cause of the issue, but launch/patient/*.read is not a valid scope.

Change FROM:
scope=openid%20profile%20patient/\*.read%20launch/patient/\*.read%20launch/patient

Change TO:
scope=openid%20profile%20patient/\*.read%20launch/patient

**Comment by tthai4** [comment]
Hi Torin,
Below are the steps that was taken:

Step 1:  Modifed the scope in the authorize URL as suggested (see authorize URL below):

https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=https://dev-aspire.partners.org&aud=https%3A%2F%2Fapsandbox.fhirapi.athenahealth.com%2FdemoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL2Rldi1hc3BpcmUucGFydG5lcnMub3JnIiwiZ3JhbnRfdHlwZXMiOlsiYXV0aG9yaXphdGlvbl9jb2RlIl0sImlzcyI6Imh0dHBzOlwvXC9teWRhdGEuZ2VoZWFsdGhjYXJlLmNvbSIsInJlZGlyZWN0X3VyaXMiOlsiaHR0cHM6XC9cL2Rldi1hc3BpcmUucGFydG5lcnMub3JnIl0sInRva2VuX2VuZHBvaW50X2F1dGhfbWV0aG9kIjoiY2xpZW50X3NlY3JldF9iYXNpYyIsInNvZnR3YXJlX2lkIjoiMS4wLjAiLCJuYXRpdmVfY2xpZW50IjpmYWxzZSwiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tXC9vYXV0aDIuY2xhaW1zXC9hcHBfaWQiOiIxY2FkZDU4NC1lMTgzLTQ1MWItYjRiMS0zMmI5ZWY4ODAxNzgiLCJleHAiOjE5NDQ2NjM0NTgsImNsaWVudF9uYW1lIjoiQXNwaXJlQXBwIiwiaWF0IjoxNjI5MTMwNjU4LCJjb250YWN0cyI6WyJ0dGhhaTRAYndoLmhhcnZhcmQuZWR1Il0sInJlc3BvbnNlX3R5cGVzIjpbImNvZGUiXX0.oVwlFk6JUzWRFKQ19uquJx3R-FIp4XcXmFseYGzteNuRYYLzp3_omE0n9N-in1i8he9s9cWoOfMiaEdybnvc7Ek8Tbm9qtM2harzhQabFJLnye6hKggNskspd9mZNh4O53ZIFz-9HDt7srQ8Vxkm8-n6y5Dje5XlFNY83Wtsyvg

Step 2:  Selected "Work Account", entered the sample provider login credential and was directed to the Patient Access page.  
Step 3:  Entered "Tom" in the "First Name" field and click Search button (i.e. patient Tom Reed is returned)

Step 4: Get the authorizationCode associated with this Tom Reed patient 

Step 5: Replaced the value of the "code" key in the request body and click Send button (this is done in Postman)

Getting the same error as stated previously.

Best,
Tien Thai

**Comment by tthai4** [comment]
Torin,
Any update on this issue?  Thank you very much for your help.

Best,
Tien Thai

**Comment by Torin-Shepard-athena** [comment]
@tthai4 We are not able to reproduce this issue with out client ids and redirect URLs.  Please send email to athenaInterop@athenahealth.com so it will be possible to work with you directly to schedule a time to have you share your screen and troubleshoot.

**Comment by tthai4** [comment]
Torin,

I am a bit confused as  both client id and redirect URL are included in the authorize URL that I provided earlier.  Thank you.

**Comment by Torin-Shepard-athena** [comment]
@tthai4 Since I, others athena do not have your client secret (please do not give it to us or anyone else) and also do not have access to your redirect URL, we are not able to follow the exact same steps you are using.

Here is the best suggestion I have before scheduling a call to troubleshoot with you. Try registering another app on our Dev Portal with redirect URL = https://httpbin.org/anything.  This should allow you to follow the exact process described at https://mydata.athenahealth.com/access-the-apis.

Put the authorize URL with this redirect_uri and new client_id into Chrome, follow the same process to authenticate and select the patient.  You should get the auth code in your browser when httpbin.org/anything receives it from our apsandbox.

Copy auth code from Chrome into Postman and POST to apsandbox token endpoint using the new client id and secret.

If you are successful with these steps, it may give us helpful clues about what might be different with your redirect_uri=https://dev-aspire.partners.org.

**Comment by tthai4** [comment]
Hi Torin,
Thanks for your response.

I have tried what your suggested but still got the same error.  Below are steps that I did:

1. Add new app and obtain client_id and client_screte
2. Construct authorize URL (see below):
https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=https://httpbin.org/anything&aud=https%3A%2F%2Fapsandbox.fhirapi.athenahealth.com%2FdemoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL2h0dHBiaW4ub3JnXC9hbnl0aGluZyIsImdyYW50X3R5cGVzIjpbImF1dGhvcml6YXRpb25fY29kZSJdLCJpc3MiOiJodHRwczpcL1wvbXlkYXRhLmdlaGVhbHRoY2FyZS5jb20iLCJyZWRpcmVjdF91cmlzIjpbImh0dHBzOlwvXC9odHRwYmluLm9yZ1wvYW55dGhpbmciXSwidG9rZW5fZW5kcG9pbnRfYXV0aF9tZXRob2QiOiJjbGllbnRfc2VjcmV0X2Jhc2ljIiwic29mdHdhcmVfaWQiOiIxLjAuMCIsIm5hdGl2ZV9jbGllbnQiOmZhbHNlLCJodHRwczpcL1wvbXlkYXRhLmdlaGVhbHRoY2FyZS5jb21cL29hdXRoMi5jbGFpbXNcL2FwcF9pZCI6Ijg2MDkwOTk5LTkzM2EtNGYxYS1iYWUyLTMyNWVlN2ZkNTY2YyIsImV4cCI6MTk0NTAyMDM2NywiY2xpZW50X25hbWUiOiJBc3BpcmUgQXBwMiIsImlhdCI6MTYyOTQ4NzU2NywiY29udGFjdHMiOlsidHRoYWk0QGJ3aC5oYXJ2YXJkLmVkdSJdLCJyZXNwb25zZV90eXBlcyI6WyJjb2RlIl19.Ysrvky1xVnVaEojIaqeiATdsQPvJWkBcdHIaR9s2_FO6b1QcolXtNqKr98ghk2a3t_-ZIA9C2hAcxjJlq4PqZ00_Jl9ktzsJa7J3syiOJyh1nwu8tXehB7Uaz46Mz9u-R3SeRX96u4dBvyVnkB_10DSZOFSz1le6uuE7tsqrbZI

3. Select Work Account and enter test userid/password (i.e. hwinston@sboxprovtenant.com)
4. Search for Tom Reed patient and obtain authorizationCode
5. Replaced client id, client secrete and authorizationCode as instructed
6. Click Send button but still got the same error. 
![Capture](https://user-images.githubusercontent.com/57362692/130286076-174001e4-ce4b-4640-8082-1088d4ee383b.JPG)

**Comment by tthai4** [comment]
Torin,
Can you please provide me any update you might have?  Many thanks for your help.

Regards,
Tien Thai

**Comment by Torin-Shepard-athena** [comment]
The token POST request is rejected when the authorization code is not yet associated with selected patient context.

launch/patient scope requires patient context to be set. If you do not click the Select Patient button (at least one of these buttons when multiple patients are listed), the internal process is not completed to associate the auth code with a selected patient.

Requests to the authorize endpoint require redirect_uri parameter.  Valid authorization codes should be extracted from the response given to the redirect_uri.
