### ISSUE TITLE
Payment status is "waiting for payment" after posting payment

### ISSUE THREAD

**Issue by rahul-chetu** [athenahealth/apiserver-athenaFlex#204]
We have posted the payment and received the success response from API, but still payment status is "waiting for payment" in the centricity application UI.
Please let us know how we can verify the payment?

Recieved response from the API-
{"resourceType":"Parameters","parameter":[{"name":"message","valueString":"The operation is successful."}]}

**Comment by Torin-Shepard-athena** [comment]
@rahul-chetu
The response to successful $PostPayment contains HTTP header Content-Location with the URL to read the newly posted payment.
The $PostPayment operation does not modify the bill payment status of the visit.
After successful $PostPayment, you can always search for all $Posting resources for the patient.
GET [base]/$Posting?subject={patientid}

**Comment by AjeetYadav07** [comment]
Closing this issue, if you have any query please raise a new ticket.
