### ISSUE TITLE
Sample patients with data

### ISSUE THREAD

**Issue by jdkizer9** [athenahealth/apiserver-athenaFlex#205]
I've been able to generate an access token for the `athenainterop@aol.com` user and I'm successfully able to fetch the `Patient` resource. However, performing a search operation for other resource types (e.g., `Observation`, `Immunization`) return empty bundles. Are there any sample patients that contain sample data?

**Comment by AjeetYadav07** [comment]
Marking this issue as closed. Please reopen if you still face any issues.
