### ISSUE TITLE
Time Slot unavailable

### ISSUE THREAD

**Issue by BYUSHC** [athenahealth/apiserver-athenaFlex#206]
Within athenaPractice we have a provider schedule template with a 15 minute slot (time slot = 'unavailable').  However, when when we pull all the 'available' slots for this provider, this unavailable shows as available.   How do we scrub these unavailable slots from the response?

![PSS una](https://user-images.githubusercontent.com/88341774/132399415-a247c6ea-3836-48e3-9b75-2a970707504f.jpg)
[PSS JSON.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/7123890/PSS.JSON.txt)

**Comment by Torin-Shepard-athena** [comment]
Sorry for the delayed response.  We believe the current Slot API does not support maximum appointments per time slot feature that is available in the scheduling module in the core product.  A work item has been created to consider for a future release.

**Comment by AjeetYadav07** [comment]
This issue has been responded and we have not received further communication from customer end. Marking as closed.
