### ISSUE TITLE
Portal password reset

### ISSUE THREAD

**Issue by dolson911** [athenahealth/apiserver-athenaFlex#212]
The portal password reset for the developer portal (https://mydata.athenahealth.com/home) does not work. When selecting the link for the reset and following the instructions, the UI states that "You can't reset your own password because password reset isn’t properly set up for your organization."

How can I reset the password to get back into our account (created a long time ago). I can create a new account since it says I have one under my existing email.

To be sure, we also have an account for the clinicals API. Is that causing a problem with the Flex API credentials?

BTW our athena handlers said to log this issue here...

**Comment by Torin-Shepard-athena** [comment]
We received confirmation the password reset was completed successfully.
