### ISSUE TITLE
To embed a button on athenahealth EHR

### ISSUE THREAD

**Issue by viku1996chetu** [athenahealth/apiserver-athenaFlex#214]
Hello Team,

We want to embed a button on AthenaHealth EHR.
When this button is clicked, we would want to launch another web application.

Below are some questions:

1. Is there a way to do this using FHIR or FHIR smart-app-launch (http://www.hl7.org/fhir/smart-app-launch/)? 
2. If yes, can you please guide us to some documentation and resources?
3. If not, by when can we expect this feature?
4. Also, if not through FHIR, is it possible to do it through any other means? If yes, can you please point us to some appropriate resources.

Your quick response will be much appreciated.

**Comment by viku1996chetu** [comment]
Thank you @Torin-Shepard-athena 
Do you have this **MEL_LAUNCH_SMARTAPP** available in sandbox
How can we simulate MEL expression/quick text 
for development using sandbox.

Any pointer will be greatly appreciated.

**Comment by Torin-Shepard-athena** [comment]
@viku1996chetu 
You can simulate the funcationality by using FHIR API Server endpoint to create a launch session.

Follow process at https://mydata.athenahealth.com/access-the-apis to get an access token.

POST request to {base_fhir_url}/session/create with valid response body

POST to https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/session/create
Authorization: Bearer Token {access_token}
Headers: Content-Type=application/json
Request Body
``` json
{
"user": "hwinston@sboxprovtenant.com",
"ehrSystem": "cps",
"patientId": "1239620410000620",
"aud": "https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir"
}
```

NOTE: 1239620410000620 = Patient.id for test patient Walter Caldwell.

Sample successful response:
``` json
{
"code": "launch_code_from_session_create_endpoint"
}
```

Now you can invoke your SMART on FHIR application with this launch code.

https://{SMART_App_Base_URL}/?launch={launch_code_from_session_create_endpoint}&iss=https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir

The SMART app must perform 2 requests to FHIR Server to get access token.

SMART app does GET request to FHIR Server authorize endpoint as the first step after being invoked with launch code.
Include launch in the scope parameter.
https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?client_id={SMART_App_client_id}
&state={state_value}
&redirect_uri={SMART_App_redirect_uri}
&response_type=code%20id_token
&response_mode=form_post
&aud=https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir
&disable_userselection=true
&launch={launch_code_given_to_invoke_SMART_App}
&scope=offline_access%20openid%20profile%20user%2F*.read%20**launch**

NOTE: {launch_code_given_to_invoke_SMART_App} is the same as {launch_code_from_session_create_endpoint}

SMART_App_redirect_uri will receive form data response from API Server authorize endpoint with {auth_code_for_launch_session} and state.

SMART app exchanges auth code for access token.
POST to https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/token
Authorization Header = Basic {SMART_App_client_id}:{SMART_App_client_secret} (Base64-encoded)
grant_type=authorization_code
redirect_uri={SMART_App_redirect_uri}
code={auth_code_for_launch_session}

SMART app will receive access_token that is authorized for the user and patient context specified in the launch session/create request.

**Comment by AjeetYadav07** [comment]
This issue has been responded and no further communication received, Marking as closed.
