### ISSUE TITLE
Sandbox down, or at least the client_credential auth flow down

### ISSUE THREAD

**Issue by Roger-Geacom** [athenahealth/apiserver-athenaFlex#215]
Tried hitting the auth endpoint to get an access token this morning(8:30 CT) and am getting an error. Nothing is changed from the last week when it was working. Tried both through our software and then through Postman, but getting the same error for both. 

These worked yesterday, so I'm sure they are correct, but I'll include them anyways: 

Endpoint: https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/token?grant_type=client_credentials&scope=user%2F*.*

Username: hwinston@sboxprovtenant.com
Password: TestProvider!@

Endpoint: 
https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/token?grant_type=client_credentials&scope=user%2F*.*

`
      <title>502 - Web server received an invalid response while acting as a gateway or proxy server.</title>

    
    
    <fieldset>
      <h2>502 - Web server received an invalid response while acting as a gateway or proxy server.</h2>
      <h3>There is a problem with the page you are looking for, and it cannot be displayed. When the Web
	      server (while acting as a gateway or proxy) contacted the upstream content server, it received an
	      invalid response from the content server.</h3>
    </fieldset>

`

**Comment by Roger-Geacom** [comment]
Update: 10:55 CT, Access tokens are back up, not sure what happened. Something must have had an outage.

**Comment by Torin-Shepard-athena** [comment]
@Roger-Geacom There was an unexpected outage.  The athenaPractice JBoss server was restarted and appears to be working properly again.
