### ISSUE TITLE
Oauth2 authorize URL for Prod

### ISSUE THREAD

**Issue by ansuman-logicoy** [athenahealth/apiserver-athenaFlex#216]
I have tested my application in sandbox and now i have clients production details with username and password which i can access from only restricted server.

What should be my SMART on FHIR authorize url which should be publicly accessible.

**Comment by deepak-athena** [comment]
Hello @ansuman-logicoy ,

#174 describes the process to move apps from athena API Sandbox to customer’s test and production environments. Please do have a look there.
-Regards, Deepak.

**Comment by AjeetYadav07** [comment]
Closing this issue, if you have any query please raise a new ticket.
