### ISSUE TITLE
Having trouble scheduling appointments

### ISSUE THREAD

**Issue by Roger-Geacom** [athenahealth/apiserver-athenaFlex#217]
I tried using some of the examples from past closed issues, but they don't seem to be working for me. I keep getting the error:         diagnostics value="No slot found for given details to create appointment." . This is extra confusing because I'm using the apsandbox which from my understanding of the docs shouldn't have slots. Unless I'm missing something. 

I managed to query some demo slots from the apsandbox, and tried including it in one of my appointment request but it is still failing. At this point I think I'm stuck. 

Details on my request: 

url: https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Appointment?_format=xml

JSON payload: 
`
{
    "resourceType": "Appointment",
    "type": "test",
    "start": "2007-10-14T15:00:00.000Z",
    "end": "2007-10-14T15:15:00.000Z",
    "minutesDuration": "15",
    "slot": {
        "reference" : "Slot/622467"
    },
    "participant": [
        {
            "actor": {
                "reference": "Location/FAC-3"
            }
        },
        {
            "actor": {
                "reference": "Patient/1442678385700620"
            }
        },
        {
            "actor": {
                "reference": "Practitioner/1588761792000070"
            }
        }
    ]
}
`

My question is what am I missing to be able to schedule appointments? 

Thanks for the help, 
Roger

**Comment by Roger-Geacom** [comment]
Just want to add a second question onto here, so maybe then both can be answered in the same go. I see a lot of the endpoints can't be created/updated through the apis: Slot like above, but also Encounter, Family History and a whole host of others. Our system is meant to be used in the practice to record/update some of this info, is there any way to get be able to write this data or is it not possible?

**Comment by AjeetYadav07** [comment]
@Roger-Geacom currently slot and some other APIs are not supported for write operation. Slots are available to book the appointment from 12 dec 2021 to 27 feb 2022 between 9.00 am to 5.00pm. Payload are attached for the same
[ApptCreate_payload.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/7827343/ApptCreate_payload.txt)
.

**Comment by Roger-Geacom** [comment]
Thanks for the info! having some sandbox slots to write to is good to know.
