### ISSUE TITLE
How to access DEANumber via Practitioner

### ISSUE THREAD

**Issue by AOCjcarr** [athenahealth/apiserver-athenaFlex#218]
We are working with a PDMP vendor that needs to validate authorization based on DEA number.
We are passing to them the PVID, and they are querying Practitioner which they do for other systems and nothing is returning.

I did do a test on a provider that I confirmed has a DEANUMBER listed on the USR table, and it is not being picked up.

I am not  sure this should be included always in Practitioner, but is there a way it would be requested to include the DEA?

**Comment by Rinkal-jain** [comment]
Currently Practitioner resource does not have any mapping to DEANUMBER. 
Although we capture DEANUMBER as part of user registration.
DEANUMBER will be mapped to identifier as part of enhancement for V22 release.

**Comment by AOCjcarr** [comment]
Thanks for the info!  Glad it will be included in v22.

Unsure about the User Registration comment for current setup though as that is not part of FHIR resources, so not sure how that may apply or would be used/accessed.
We likely have to wait for V22 for this option


Thanks,
Jeremy Carr


CELL 773.580.0099
***@***.******@***.***>

**Comment by AjeetYadav07** [comment]
This issue has been responded and no further communication received. Marking as closed.
