### ISSUE TITLE
Unable to pull Location resource  403:  Error Processing: Not Authorized

### ISSUE THREAD

**Issue by AOCjcarr** [athenahealth/apiserver-athenaFlex#219]
We are unable to pull the location resource received a 403 forbidden/not authrorized
https://apihi.emrconnect.org:9443/hiAPIServer/fhir/Location/1764003129410450

The access token is valid as when I do a practitioner call it successfully is returning data

FHIR Jboss logs are showing
"2021-11-10T12:51:06,265	ERROR	(462-CVS.docmap	ba7943d2-060d-466a-84b5-f779d9036102	)	[AccessControlIntercepter]	ACI694E11: An unexpected error occurred in AccessControlIntercepter before processing this request.
URL: https://apihi.emrconnect.org:9443/hiAPIServer/fhir/Location/1764003129410450?_format=json&_summary=data"

Verified location 1764003129410450 exists and is active on the LOCREG table.

Not sure what may be blocking, I can't imagine it is user rights as the user can get Practitioner and patient info with no issue

**Comment by Torin-Shepard-athena** [comment]
@AOCjcarr 
Please turn on debug level logging ant look at all lines in FHIR Server log file that have the same thread id for the FHIR Location query that causes ACI694E11 error message.

In the above example, you would want to search for all occurrences of ba7943d2-060d-466a-84b5-f779d9036102 to see what happened while processing that Location call.

**Comment by AjeetYadav07** [comment]
We are closing this issue, if you have any query please raise a new ticket.
