### ISSUE TITLE
Breaking change to permisions.

### ISSUE THREAD

**Issue by Roger-Geacom** [athenahealth/apiserver-athenaFlex#222]
Greetings, it appears in the last week when the server was down, there was a change to the permissions returned to the account with the email:  hwinston@sboxprovtenant.com. (the "native flow" test account). 

Request url for context: {{url}}/oauth2/token?grant_type=client_credentials&scope=user%2F*.* 

Previously this account had permissions to write observations to the sandbox. Now it appears those permissions have been removed? This is problematic for our testing purposes, as we are currently working on nailing down our workflow for these observations. 

I have confirmed that I still get write access to our client's production version, but it is not ideal to test things out on the production version.   

Is this an intentional and permanent change? If not, is there a timeline for this getting fixed?

**Comment by athena-Interop** [comment]
@Roger-Geacom Thank you for bringing this to our attention.  The permission to write resources using FHIR APIs has been restored in apsandbox.fhirapi.athenahealth.com.
