### ISSUE TITLE
Our IT department needs a EULA or written consent so we can use the Trial (Non Prod) version of PracticeSolutions v19/v20

### ISSUE THREAD

**Issue by nharrar** [athenahealth/apiserver-athenaFlex#226]
Our IT department needs a EULA or written consent so we can use the Trial (Non Prod) version of PracticeSolutions v19/v20. Does anyone know where we can find proof that the trial license or non prod instance is free to use?

**Comment by deepaktiwari29** [comment]
Closing this issue as there are no more requests/acivities on this thread.
