### ISSUE TITLE
Point of Contact for Partnership Agreements with athenaFlex

### ISSUE THREAD

**Issue by Tifani-Ng-Zocdoc** [athenahealth/apiserver-athenaFlex#228]
Hi athenaFlex,

I am a Program Manager for Integrations at Zocdoc. We are currently looking at building an integration between Zocdoc and athenaFlex's scheduling components. Could you provide me an athenaFlex Point of Contact that Zocdoc can reach out to for establishing Partnership Agreements between both parties? Feel free to send me an email at: tifani.ng@zocdoc.com to connect on this question.  

Thanks,
Tifani

**Comment by Torin-Shepard-athena** [comment]
Please contact [Geoff Lay](mailto:glay@athenahealth.com) or [Leslie Twine](mailto:ltwine@athenahealth.com) for help with information about partnership agreements for athenaPractice/athenaFlow.

**Comment by AjeetYadav07** [comment]
@Tifani-Ng-Zocdoc closing this issue, if you have any query please raise a new ticket.
