### ISSUE TITLE
Do we know the release date for v22 which would Support FHIR R4? 

### ISSUE THREAD

**Issue by pratik-shah-zocdoc** [athenahealth/apiserver-athenaFlex#229]
Hi @athena-Interop,

What would be a tentative release date for v22 which would support FHIR R4? 
As per my understanding, the current version is based on DSTU2. And I wanted to decide if we should start building our application to the current version or wait for the latest version release?

**Comment by AjeetYadav07** [comment]
@pratik-shah-zocdoc  V22 will be released by June 2022.
