### ISSUE TITLE
CCDA inclusion of Assessment with /Condition

### ISSUE THREAD

**Issue by AOCjcarr** [athenahealth/apiserver-athenaFlex#232]
@Torin-Shepard-athena and Team

In reviewing CCDA's generated with DSTU2  (v20.1) a site has noted that Problem records do not include the history of assessments related to each problem stored on the ASSESS table.  
I am trying to identify if there is any HL7 or other documentation that I can point to indicating that this would not or should not be included in the problem records or elsewhere in the CCDA.  

Or is this an item not currently available in DSTU2 that may be included in V4 when it is released?

Ultimately just looking for documentation to provide backing that this is not an issue in how we are generating the files and if applicable, help the clinic understand why this portion of data is not included 

Thanks!

**Comment by Torin-Shepard-athena** [comment]
@AOCjcarr
This is a known concern with different solutions between DSTU2 and R4.

V20 with DSTU2: Database trigger TR_ASSESS_OBSENTRY on ASSESS table can be enabled to populate OBS table using OBS term named ASSESSMENT. This trigger will copy Problem Assessments data to OBS table and make sure OBS table is maintained with accurate copy of new/changed/removed assessments. CDA 2.1 CDA Generator is configured to include data from this OBS term in Assessment and Plan part of CCDA Treatment Plan section.

V22 with R4: FHIR server is enhanced to support FHIR ClinicalImpression resource type. CDA 2.1 Generator is configured to include assessments data from both OBS and ASSESS tables. V22 upgrade will disable the ASSESS table trigger that copies/updates OBS table.

**Comment by AOCjcarr** [comment]
Great thanks for the additional info Torin!!   That is what we needed to know.  Knowing that it will be integrated with V22 should suffice the need for the time being in this case!

Appreciate the info!

Thanks,
Jeremy Carr

CELL 773.580.0099
***@***.******@***.***>
