### ISSUE TITLE
Construct the Access My Data URL

### ISSUE THREAD

**Issue by AOCrpunzalan** [athenahealth/apiserver-athenaFlex#233]
I have added my redirect and client id to the following url but getting a DNS_PROBE_FINISHED_NXDOMAIN in my browser.  Is this the proper url?  If so, I will continue down this path and would appreciate your thoughts on  troubleshooting the DNS error above.  If not, please read further below.

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=[redirecturl]&aud=https%3A%2F%2Fapsandbox.fhirapi.athenahealth.com%2FdemoAPIServer&client_id=[clientid]

On another note, after looking through some of the past issues, I came across this url and tried it.  To my surprise I was able to access the Access My Data screen with the Work account option.  After I clicked on Work account, I entered the test provider credentials and after hitting log in, I was brought to my app.  However, I thought I would be presented the Patient Access screen with a listing of test patients as per the directions on the dev portal.  Can you please guide in getting to that screen and eventually obtaining a patient authorization code?

https://apsandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20user/*.*%20offline_access&response_type=code%20id_token&redirect_uri=[redirecturl]&aud=https%3A%2F%2Fapsandbox.fhirapi.athenahealth.com%2FdemoAPIServer&client_id=[clientid]

**Comment by Torin-Shepard-athena** [comment]
@AOCrpunzalan 
The value of the scope parameter controls whether you will see the patient access selection screen.

With user scope, the authenticated user can access multiple patients based on their permission for sensitive patients and which patients may have a user exclusion list configured in Registration.  Our FHIR server automatically enforces these permissions when responding to FHIR requests.  Responses do not include data that is not authorized for a given user associated with an access token.

With patient scope, the patient selection screen is presented so the access tokens are linked to specific patient context.

Change the scope parameter from user to patient scopes, and you should be prompted to search for and select a patient.  The available patients are limited to the patients the authenticated user is allowed to access.

With our apsandbox server, the published sample provider (work) account is authorized to access all patients in the athenaPractice demonstration DB.

https://mydata.athenahealth.com/access-the-apis has a note about authorization scopes as part of step 8 of the provider workflow.

The sample call to the authorize endpoint requests an access token for a specific patient context by specifying the OAuth2 scopes for patient context (patient/*.read and launch/patient). These scopes will prompt you to select a patient. If you do not want to establish a patient context with your access token, then you may use other scopes that are available as part of the SMART on FHIR.

Here is the corrected link to the scopes from the SMART App Launch Framework Implementation Guide we are currently supporting.
http://hl7.org/fhir/smart-app-launch/1.0.0/scopes-and-launch-context/index.html

**Comment by AjeetYadav07** [comment]
@AOCrpunzalan 
Hoping we have answered your question, marking this issue as closed. If you have any query please register new issue.
