### ISSUE TITLE
Create Condition for a patient

### ISSUE THREAD

**Issue by jeffbandre** [athenahealth/apiserver-athenaFlex#234]
Is it possible to create a condition for a patient using the sandbox provider credentials (hwinston@sboxprovtenant.com)?
I generated the authorization code using Work account, and also generated the access token.
I tried GET patient and it works fine with the access token.

I then tried Create Condition and it returns an error "Not Authorized".

Here's my Postman request for Create Condition.
POST    https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Condition
Headers:
Authorization     Bearer eiJ0eXA.....

Body:
{
     "clinicalStatus": {
        "coding": [
            {
                "system": "http://hl7.org/fhir/ValueSet/condition-clinical",
                "code": "active",
                "display": "Active"
            }
        ],
        "text": "Active"
    },
    "code": {
        "text": "Adverse effect of vaccines and biological substances",
        "coding": [
            {
                "system": "urn:oid:2.16.840.1.113883.6.90",
                "code": "T50.Z95A"
            }
        ]
    },
    "category": [
        {
            "coding": [
                {
                    "system": "http://hl7.org/fhir/condition-category",
                    "code": "problem-list-item",
                    "display": "Problem List Item"
                }
            ],
            "text": "Problem List Item"
        }
    ],
    "subject": {
        "reference": "Patient/1902008249235680"
    },
    "onsetDateTime": "2020-12-27",
    "onSetPeriond": {
        "end": "2020-12-27"
    },
    "note": [
        {
            "text": "This is the comment for the note."
        }
    ]
}

Returned body:

{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Outcome null</span></td><td width=\"42%\"><span class=\"text-muted\"><table><thead><tr><th>#</th><th>Severity</th><th>Type</th><th>Detail</th></tr></thead><tbody><tr><td>1</td><td>ERROR</td><td>PROCESSING</td><td>Not authorized</td></tr></tbody></table></span></td></tr></tbody></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Not authorized"
        }
    ]
}

**Comment by AOCjcarr** [comment]
@Torin-Shepard-athena   Not sure if you have someone that can assist with this question. Our vendor is attempting to test out Create Condition statement and receiving a authentication error, however successfully able to do a ready with the credentials.

Is there a process to test create statements before we test them in a regular environment?

Also, they are hoping to do some testing against r4 functionality that will be available with V22.   Just confirming is this the proper URL they should be connecting to for that?   
https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir

Looking at the metadata  I am not seeing any indication of version other the fhirVersion value="1.0.2" notation in the conformance, but may be looking at the wrong item so wanted to be sure.

**Comment by Torin-Shepard-athena** [comment]
@AOCjcarr @jeffbandre 
cpsapisandbox = 12.3
apsandbox = V20 
ap22sandbox = V22

FHIR Clinical Writes should be working on the V20 and V22 machines.

An additional path component is required to use FHIR R4 APIs in V22 which will support both FHIR versions to allow customers time to transition any FHIR apps from DTSU2 to R4.
https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir = DSTU2
https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4 = R4

Our FHIR R4 API documentation is now available for everyone to use.  Please take time to visit the updated Dev Portal at https://mydata.athenahealth.com/home

**Comment by AOCjcarr** [comment]
Thanks Torin!
@jeffbandre    based on the comment could you try again with a connection to the ap22 sandbox?  It does sounds like the 12.3 sandbox that you were accessing does not facilitate the Create statements, but the others should.     The ap22  site would be the site we are targeting for this project, and as Torin mentions you can specify DSTU2 or R4 based on the path used in the request.

**Comment by Torin-Shepard-athena** [comment]
@jeffbandre Please confirm the scopes you are requesting in your authorize endpoint URL.  If you request only patient/*.read, then the access token will not be authorized to perform writes.  You can use patient/*.* to request write permissions.

Also, make sure you use the proper Patient.id value in the Condition resource in the POST request body.  The sample personal account login credentials are associated with test patient Walter Caldwell.  You will need to use his Patient.id because the access token is authorized to access only data for this test patient.

**Comment by jeffbandre** [comment]
@Torin-Shepard-athena I tried changing to patient/*.* in the access URL, but I got an invalid client id error and access was revoked.

My Access URL:
https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.*%20launch/patient&response_type=code&redirect_uri=https://httpbin.org/anything&aud=https%3A%2F%2Fap22sandbox.fhirapi.athenahealth.com%2FdemoAPIServer&client_id=<myclient_id>

Error message
![image](https://user-images.githubusercontent.com/54361692/170492292-25811992-e524-42ef-944a-244aca9eb769.png)

**Comment by Torin-Shepard-athena** [comment]
@jeffbandre Some configuration maintenance was done on the ap22sandbox machine.  Please retry.

**Comment by jeffbandre** [comment]
@Torin-Shepard-athena It's working now. Thanks!

**Comment by Torin-Shepard-athena** [comment]
@jeffbandre @AOCjcarr 
I hope we will add more information in our API documentation about FHIR Clinical Writes in the future.

The Practitioner that authors/asserts clinical data is a required item for all FHIR Clinical Writes.

Business rules for processing Condition.code:
- Query ProblemDescriptionMap table where CommonDescription = Condition.code.text
- If input Condition.code.text does not match the common description for any problem from the KnowledgeBase update, then proceed to use codes to try to find a match.
- At least 2 Condition.code.coding elements with different coding systems are required to create a Condition if the text is not recognized.
  - ICD-9 + ICD-10
  - ICD-10 + SNOMED
  - ICD-9 + SNOMED
- Input pair of codes must match a row in ProblemDescriptionMap table that links to both of the MasterDiagnosis rows corresponding to the input codes.

You can examine the codes and descriptions in these 2 tables in athenaPractice database to see how the KnowledgeBase associates the "common descriptions" with various ICD-10, ICD-9, and SNOMED codes.
