### ISSUE TITLE
Smart on FHIR ; Launch Support

### ISSUE THREAD

**Issue by cbarrette9** [athenahealth/apiserver-athenaFlex#235]
Hi:

I am wondering which provider Smart on FHIR launch sequence this supports; Standalone or EHR Launch? From http://www.hl7.org/fhir/smart-app-launch/app-launch.html#top-level-steps-for-smart-app-launch
describes Standalone and EHR as launch sequences.  

We have an app configured with other EHR's but its designed specifically for an EHR Launch and want to make sure that is the supported launch mechanism before we work getting a customer connected.

Appreciate any insight.  Thanks.

**Comment by Torin-Shepard-athena** [comment]
@cbarrette9 
athenaPractice and athenaFlow suport both Standalone and EHR Launch.

Please review the information in #214.

**Comment by AjeetYadav07** [comment]
Marking this issue as closed, if you have any query please raise a new ticket.
