### ISSUE TITLE
Our queries on Integration with Athena Health Centricity

### ISSUE THREAD

**Issue by ahsankcg** [athenahealth/apiserver-athenaFlex#239]
Hi,
We need to build an interface with Athena Health Centricity APIs for the following Resources:
- Get Patients
- Get Appointments
- Create Patient
- Create Appointment
- Get Providers, Locations and Appointment Types

We have figured out almost most of these resources APIs and their uses but we have few queries which are blocking our progress with integration:

- What should be the correct scope for integration with the resources mentioned above? Currently we are using this scope:
    `openid%20profile%20patient/*.read%20launch/patient%20offline_access` 
  But it seems not enough.

- What is the role of slots with Appointment? Currently we are not able to create appointment because we are getting this error: 
   `No schedule found for given resource id`
  So, it seems its related to slots info in Appointment that we are missing while creating appointment. There is another issue that we  created about this:
https://github.com/athenahealth/apiserver-athenaFlex/issues/238
Also, we tried to access Slot list API with this URL:
https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Slot
But its giving 403 forbidden

Please help us resolve these issues so that we can move forward with our integration. 

Thank You

**Comment by AjeetYadav07** [comment]
@ahsankcg 
To support read and write operation correct scope is
openid%20profile%20patient/*.*%20launch/patient%20offline_access or 
openid%20profile%20user/*.*%20launch/patient%20offline_access. Slot is a FHIR resource implemented in hl7 which is used to create some slot based on provider scheduled. currently we are not supporting Write operation for Slot.
[Github 217](https://github.com/athenahealth/apiserver-athenaFlex/issues/217)
[Github 225](https://github.com/athenahealth/apiserver-athenaFlex/issues/225)

**Comment by ahsankcg** [comment]
@AjeetYadav07 Hi
Thanks for your response !
I am getting this by using both of the scopes you recommended 
![image](https://user-images.githubusercontent.com/74238436/177129673-d4ad71f9-35a7-4828-b13b-0b15837183b1.png)

**Comment by AjeetYadav07** [comment]
@ahsankcg 
Below are defined scopes in authorization request :

Read only access of APIs in user scope : openid%20profile%20user/.read%20launch/patient
Write only access of APIs in user scope : openid%20profile%20user/.write%20launch/patient

Read only access of APIs in Patient workflow scope :  openid%20profile%20patient/*.read%20launch/patient 
Write only access of APIs in patient workflow scope : openid%20profile%20patient/*.write%20launch/patient

offline_access in scope param value is used to generate refresh token. Refresh token is used when the requirement is to continuous hit of APIs more than one hours. Access token is valid for 60 min only. detail discussion added in 
[Github 173](https://github.com/athenahealth/apiserver-athenaFlex/issues/173)
[Github 176](https://github.com/athenahealth/apiserver-athenaFlex/issues/167)

**Comment by ahsankcg** [comment]
@AjeetYadav07 Hi
Thanks again for your response really appreciate. 
I think the correct scope that will fulfill our requirements is `openid%20profile%20user/*.*%20launch/patient%20offline_access`. I have successfully generated access token with it. Also yes we need `offline_access` to ensure continuous integration.

**Comment by AjeetYadav07** [comment]
Hi @ahsankcg 
Yes, scope "user/*.*" will provide permission to read and write for all APIs.

**Comment by Torin-Shepard-athena** [comment]
@ahsankcg

The latest comment at end of issue #140 mentions there is a new operation that can be used to get appointment types that can be scheduled for a given practitioner.

Example: https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4/Appointment/$lookup-type?practitioner=1588761792000070
This outputs a Parameters resource with parameters array with appointment types.
Parameters.parameter[i].valueCodeableConcept.coding.code is the internal appointment type id value.

Appointment resource has another operation that will return a list of practitioners that can be scheduled for a given appointment type id.

Example: https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4/Appointment/$lookup-practitioner?type=7
This outputs a Parameters resource with parameters array with references to practitioners.

**Comment by AjeetYadav07** [comment]
Closing this issue, please raise new tickets for any queries.
