### ISSUE TITLE
What is the correct Authentication Process that allows to create patient and appointments in Centricity via APIs.

### ISSUE THREAD

**Issue by ztabani** [athenahealth/apiserver-athenaFlex#241]
Hi,

We are trying to build the interface with centricity APIs to **Get** or **Post** patients, appointments for all providers and locations from Centricity Account. But It seems we have to select patient every time we authorize the interface via provider credentials (worker process). 
Is there any scope or way to get token for all patients? This is a show stopper for our integration as we can't create appointment other than the patient selected during authorisation.

The scope we are using is this:
openid%20profile%20user/*.*%20launch/patient%20offline_access

If we remove launch/patient from it. It will give forbidden status

And if we update it with patient/*.* like:
openid%20profile%20user/*.*%20patient/*.*%20offline_access

it will give this error in the redirect url:
*Requesting for patient context access, so requested scopes must contain additional either 'launch' or 'launch/patient' to select a patient.*

So, is there any possibility that we can integrate with all patients from one token? Or we have to generate token for each patient?

Thanks

**Comment by AjeetYadav07** [comment]
Hi @ztabani 
 is there any possibility that we can integrate with all patients from one token?
Yes, there is a Native User Authentication and Authorization Workflow through which you can generate an access token which has permission to access all patients read and write.

[Native User Authentication and Authorization Workflow.docx](https://github.com/athenahealth/apiserver-athenaFlex/files/9069722/Native.User.Authentication.and.Authorization.Workflow.docx)

If you are not using our CPS Client application, provide registered application(dev portal) name to authenticate with our CPS application.

**Comment by ztabani** [comment]
Thanks @AjeetYadav07 . 
Could you please share the native user credentials for the sandbox environment?

**Comment by AjeetYadav07** [comment]
Yes, same provider credentials can be used in sandbox environment. Snapshot of postman is present in document.

**Comment by ztabani** [comment]
@AjeetYadav07 I am little bit confused about different short names like CPS, AP, AAD etc .. 
Our requirement is to integrate with Centricity. Can you please describe these short names (looks like they are different products). 
Thanks

**Comment by AjeetYadav07** [comment]
Hi @ztabani ,
The short term CPS stands for Centricity Practice Solution which is  AthenaPractice (AP). AAD is Azure Active Directory.
cpsapisandbox is v20 version sandbox and apsandbox  is version v20.2. V22 is released with FHIR R4 standard and configured in ap22sandbox.
