### ISSUE TITLE
Invalid redirect uri

### ISSUE THREAD

**Issue by festivus** [athenahealth/apiserver-athenaFlex#242]
I'm trying to do the provider workflow using the https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer. The redirecturi i specify in the authorize call is registered with my app but I get the following when logging in:

The redirect URI 'https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize/-callback' specified in the request does not match the redirect URIs configured for the application

Here is my authorize url: https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize/?aud=https://cpsapisandbox.fhirapi.athenahealth.com/demoAPIServer&response_type=code%20id_token&client_id=[ClientId]&state=mystate&scope=openid%20profile%20user%2F*.read&redirect_uri=[RedirectUri]

**Comment by Torin-Shepard-athena** [comment]
@festivus 
You are using an old version.
V12.3 cpsapisandbox
V20.2 apsandbox
V22.0 ap22sandbox

Please try with the newer apsandbox and/or ap22sandbox machines.

Can you please give the full URL to the authorize endpoint with actual values for ClientId and RedirectUri parameters?  This may enable us to help you determine the cause of your issue.

**Comment by AjeetYadav07** [comment]
Marking this issue as Closed, raise a new ticket for any further queries.
