### ISSUE TITLE
Provider authorization url

### ISSUE THREAD

**Issue by NiranjanDubule10** [athenahealth/apiserver-athenaFlex#243]
**Your question**
I am looking for a provider authorization url to call from which I can get Iss and launch parameters for authorization

For example, I need to be able to access xyz from abc but the API doesn't seem to support this.....
I want to get access token for provider access, I followed the steps given but am not able to figure out how do I get iss and launch parameters for authorization.

I have my redirect url and client id but could not figure out the url to get iss and launch values

**Comment by Torin-Shepard-athena** [comment]
https://github.com/athenahealth/apiserver-athenaFlex/issues/214#issuecomment-970721282 explains how you can simulate getting a launch code needed to invoke a SMART app using the iss and launch parameters.
