### ISSUE TITLE
Client_Credentials parameters to include

### ISSUE THREAD

**Issue by NiranjanDubule10** [athenahealth/apiserver-athenaFlex#245]
What parameters I need to include to generate token for grant type Client_Credentials ?

token url = https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/token

for now I am trying using 
cliend id, secret
or
client id, scope, redirect uri

but not able to generate access token

**Comment by AjeetYadav07** [comment]
Hi @NiranjanDubule10,
please refer to the [Github 241](https://github.com/athenahealth/apiserver-athenaFlex/issues/241). It has detailed information about the post token endpoint.

**Comment by NiranjanDubule10** [comment]
> Hi @NiranjanDubule10, please refer to the [Github 241](https://github.com/athenahealth/apiserver-athenaFlex/issues/241). It has detailed information about the post token endpoint.
Hi @AjeetYadav07 
Thank you for the referred URL. I got clear idea about it.

I do have a question is that, is there any way to where it dose not need to pass username and password for client_credential scope. Because in current scenario, I am passing username and password in Basic Auth, but I want to use client id and secret or no auth to generate a token.

**Comment by NiranjanDubule10** [comment]
@AjeetYadav07

**Comment by deepaktiwari29** [comment]
@NiranjanDubule10 As per current implementation, we would require username and password to generate a access token along with CLIENT ID & CLIENT SECRET. And we don not support any other mechanism to generate an access token without using any auth or by just using CLIENT ID & CLIENT SECRET.

**Comment by deepaktiwari29** [comment]
Closing this as we are no longer planning to add any support for the issue.
