### ISSUE TITLE
Getting visit details - charges

### ISSUE THREAD

**Issue by jschofer914** [athenahealth/apiserver-athenaFlex#247]
Hello, we are looking to obtain the charge details for a patient visit. How would I get the procedures, diagnosis and other details that could be used to build a charge for a patient visit.  I have seen the account response that provides a balance,  We are looking to gather the details behind this balance.

Thank you

**Comment by AjeetYadav07** [comment]
Hi @jschofer914,
Account resource will provide the data for patient balance whereas we have implemented new APIs like Claims, Charges and Payment etc. which will be applicable in next release of v23. Charge API will contain information specific to patient visit.

**Comment by AjeetYadav07** [comment]
Marking this issue as closed. if you have any other query, please create a new ticket.
