### ISSUE TITLE
"An unexpected error has occurred. Please try this operation again later."

### ISSUE THREAD

**Issue by muzammil-syed** [athenahealth/apiserver-athenaFlex#248]
Ref site: https://mydata.athenahealth.com/access-the-apis

How do I Generate an access token, I am able to generate authorisation code. While making request on Postman, I had the following error PFA(Img#1).

I added bearer token i.e, username(client_id) & password (client_secret) and set the body as mentioned in the instruction PFA(Img#2).

Img#1:
![image](https://user-images.githubusercontent.com/110962543/199995437-6150c6ec-88d6-4d9e-8d02-f3db64b5e2c4.png)

Img#2:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/110962543/199996485-a119a6d2-f22c-4345-ba24-eece95f684a2.png">

**Comment by muzammil-syed** [comment]
@AjeetYadav07 can you please help me on this.

**Comment by AjeetYadav07** [comment]
Hi @muzammil-syed,
The authorization workflow is different in POST mode as compare to GET mode of request for access token. please look at  [github issue 241](https://github.com/athenahealth/apiserver-athenaFlex/issues/241).

**Comment by muzammil-syed** [comment]
Okay thanks, I will look into it and close the issue if it works.

**Comment by AjeetYadav07** [comment]
Marking this issue as Closed. if you any concern, register a new ticket.

**Comment by muzammil-syed** [comment]
Okay thanks. I will raise a new one on a different problem. This is solved.
