### ISSUE TITLE
How to login to Athena Portal through API call seamless.

### ISSUE THREAD

**Issue by muzammil-syed** [athenahealth/apiserver-athenaFlex#249]
Our end goal is to make a user login into his/her Athena Portal through API call seamless.

How can we fetch authorisation code through API calls seamless or how can we bypass selecting work/patient account and enter credentials through API call.

Pictorial explanation:
PFA, We have to select account either Work or Patient, so through API call how can we select it and sign into microsoft account ?
<img width="966" alt="image" src="https://user-images.githubusercontent.com/110962543/205873095-0c578003-37aa-4e11-a284-eaa0d73ae5bb.png">

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/110962543/205874504-3fa98203-2c0b-498e-94f8-d1d5b0d759e4.png">

**Comment by areyalp** [comment]
Hi,

It was already explained in the first issue raised. You can check it on the following link https://github.com/athenahealth/apiserver-athenaFlex/issues/177#issuecomment-889323368

**Comment by AjeetYadav07** [comment]
This issue has been addressed in a call, Marking as closed.
