### ISSUE TITLE
Not able to pull data out of FHIR R4

### ISSUE THREAD

**Issue by techman2** [athenahealth/apiserver-athenaFlex#252]
We are able to pull data out of FHIR DSTU2 in Athena's Sandbox but not from FHIR R4. 

For FHIR R4 we get a success, but following response. We know this patient has Allergy based on the Athena One API and FHIR DSTU2 response.
1{
2  "link": [
3    {
4      "url": https://api.preview.platform.athenahealth.com/fhir/r4/AllergyIntolerance?ah-practice:Organization=a-1.Practice-195900&patient=806,
5      "relation": "self"
6    }
7  ],
8  "entry": [
9    {
10      "resource": {
11        "resourceType": "OperationOutcome",
12        "issue": [
13          {
14            "severity": "error",
15            "code": "invalid"
16          }
17        ]
18      },
19      "link": [
20        {
21          "url": https://api.preview.platform.athenahealth.com/fhir/r4/OperationOutcome/,
22          "relation": "self"
23        }
24      ],
25      "search": {
26        "mode": "outcome"
27      },
28      "fullUrl": "urn:uuid:61c5fd00-8f08-32c7-9330-b20567575511"
29    }
30  ],
31  "timestamp": "2022-12-08T14:37:40.000-05:00",
32  "resourceType": "Bundle",
33  "type": "searchset"
34}

It lets us authorize for all system end points but not the Patient or user ones.
All the end points are added to the scope of the app 

![image](https://user-images.githubusercontent.com/121248875/209681101-dec0799f-ae28-4f8e-873d-440a27dd185d.png)

 
![image](https://user-images.githubusercontent.com/121248875/209681130-46bd6cbf-ed3c-4d6a-886f-56c41056e88f.png)

 
![image](https://user-images.githubusercontent.com/121248875/209681142-cabf2ec6-288d-4961-85f4-ce002b147a62.png)

Here is the response from DSTU2 FHIR end point , as a proof that this patient – 806 has allergies.
Request URL
https://api.preview.platform.athenahealth.com/v1/195900/1/fhir/dstu2/AllergyIntolerance?patient=806

Response:
![image](https://user-images.githubusercontent.com/121248875/209681173-7492152a-5bb4-49b5-9fe2-5a364de4b265.png)

**Comment by Torin-Shepard-athena** [comment]
@techman2 https://github.com/athenahealth/apiserver-athenaFlex has information about FHIR APIs for athenaPractice and athenaFlow products.

Please use https://docs.athenahealth.com/api/ and https://docs.athenahealth.com/api/support to get information about FHIR APIs for athenaClinicals and athenaOne platform.

**Comment by AjeetYadav07** [comment]
Closing this issue. if you have any query, please register a new ticket.
