### ISSUE TITLE
Search by SSN

### ISSUE THREAD

**Issue by AOCjcarr** [athenahealth/apiserver-athenaFlex#253]
Is there a way to search for a patient including Social Security Number as one of the parameters to validate?   We are looking for ways to keep the searches as specific as possible to avoid multiple matches so we are ideally looking to do a search including combination of last, first, dob, gender and SSN, similar to Linklogic match.

Or is best to pull the list off of First/Last/DOB, and then a second evaluation by the requesting system to review the details returned with all matches to attempt an exact match (if SSN and Gender or address or other fields are included in the search results)

What have other system done when the athena PatientID is not known but an automated system to match patient and post observations back to the chart.

**Comment by Torin-Shepard-athena** [comment]
@AOCjcarr Search by FHIR Patient.identifier element.

https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/Patient?identifier=http://hl7.org/fhir/sid/us-ssn%7C822846624

The %7C is important for proper URL-encoding of the pipe separator character between the coding system and the value.

**Comment by AOCjcarr** [comment]
Thanks I will pass this along so they have it in case it is needed.
Closing this topic.
