### ISSUE TITLE
Error : The FHIR endpoint on this server does not know how to handle GET operation

### ISSUE THREAD

**Issue by satishjayakumar** [athenahealth/apiserver-athenaFlex#254]
I followed the steps mentioned in this link (https://mydata.athenahealth.com/access-the-apis).  
I was able to generate the access_toke but I was not able to access the API using this token.

1. Generate the token in Postman using this URL - https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/token
2. Use the token and Patient id from the above response to access the API (https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4/Patient?patientid=1983516790925600).
3. I am getting this Error response - "Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[Patient] with parameters [[patientid]]"

Also wanted to know if there is any Application or UI to check the patient data apart from accessing them from Postman ?

I have attached the screenshot for reference.
![AthenaHealthPostmanError](https://user-images.githubusercontent.com/9380111/218389598-d675fb2b-d3d2-4c36-9c3b-dd023f2c914d.jpg)

**Comment by AjeetYadav07** [comment]
@satishjayakumar 
To access patient fhir r4 resource, we are listing all supported [search parameter](https://docs.mydata.athenahealth.com/fhir-r4/StructureDefinition-athena-patient-profile.html#search-parameters). please visit on https://mydata.athenahealth.com/fhirapidoc/r4 for all fhir r4 resources profiles supported.

**Comment by satishjayakumar** [comment]
Thank you for your response. I changed the search parameter as per the document and was able to get the response.
https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4/Patient?_id=1983516790925600

One other question that I had was how do we create appointments or add clinical items to this patient ?

**Comment by Torin-Shepard-athena** [comment]
@satishjayakumar 
Please search this forum for past issues regarding "create appointments" and "create observation" or "post observation".
The CapabilityStatement shows which clinical resource types support POST request to create clinical items.
To be able to perform FHIR writes, you'll need to change your authorization request to include write scopes in addition to read scopes.
We hope to add documentation to the Dev Portal about FHIR clinical writes in the future.

**Comment by AjeetYadav07** [comment]
Marking this issue as closed. If you have any query, please create a new ticket.
