### ISSUE TITLE
Unable to login with work account 

### ISSUE THREAD

**Issue by shumon07** [athenahealth/apiserver-athenaFlex#255]
After constructing the url 
https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code&redirect_uri=https://httpbin.org/test&aud=https%3A%2F%2Fap22sandbox.fhirapi.athenahealth.com%2FdemoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL2FwMjJzYW5kYm94LmZoaXJhcGkuYXRoZW5haGVhbHRoLmNvbVwvZGVtb0FQSVNlcnZlciIsImdyYW50X3R5cGVzIjpbImF1dGhvcml6YXRpb25fY29kZSJdLCJpc3MiOiJodHRwczpcL1wvbXlkYXRhLmdlaGVhbHRoY2FyZS5jb20iLCJyZWRpcmVjdF91cmlzIjpbImh0dHBzOlwvXC9odHRwYmluLm9yZ1wvdGVzdCJdLCJ0b2tlbl9lbmRwb2ludF9hdXRoX21ldGhvZCI6ImNsaWVudF9zZWNyZXRfYmFzaWMiLCJzb2Z0d2FyZV9pZCI6IjEuMC4wIiwibmF0aXZlX2NsaWVudCI6ZmFsc2UsImh0dHBzOlwvXC9teWRhdGEuZ2VoZWFsdGhjYXJlLmNvbVwvb2F1dGgyLmNsYWltc1wvYXBwX2lkIjoiZDZmN2MxNTAtYWJjNC00ZDBjLWIxMDEtM2M3ZWQ2MjI3YjQ5IiwiZXhwIjoxOTkyMTA4NzAxLCJjbGllbnRfbmFtZSI6IkF0aGVuYUFwcCIsImlhdCI6MTY3NjQ4OTUwMSwiY29udGFjdHMiOlsic2h1YWxhbTE0MUBnbWFpbC5jb20iXSwicmVzcG9uc2VfdHlwZXMiOlsiY29kZSJdfQ.X_sckqKdv3uC9-FkGNvAGwr-63RkFH2K0I7WqR97LlIKbt7XvF1jZabCfpS-uH3MSnHBICF7hfcxZ45JIYtD5qVZXsrZLfSPdl0sj898M2lNKdl6hPJ5ECZ3MzuuXpsiOJSLuoe7WEifKgp8beUvmg7mzhdDubZK7ulu_0eoxvY

I was able to get to log in screen. Once I click on work account and sign in to Active directory I am getting following error 
-----
AADSTS50020: User account 'shualam141@gmail.com' from identity provider 'live.com' does not exist in tenant 'FHIR Sandbox - Provider Access' and cannot access the application '8109c3b1-08e5-4cb8-b5f7-02230b32ac95'(v2athenaFlex API Server-fhirprowusvm.azurehc.athenahealth.com-demo) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
------
How can i pass this step

**Comment by AjeetYadav07** [comment]
The API Access page describes 2 flows with different account credentials for getting access tokens to use FHIR APIs with athenaPractice and athenaFlow.

Provider workflow: Generate authorization code using Work account
Sample provider login credentials:
User Name: [hwinston@sboxprovtenant.com](mailto:hwinston@sboxprovtenant.com)
Password: TestProvider!@

Patient workflow: Generate authorization code using Personal account
Sample patient login credentials:
User Name: [athenainterop@aol.com](mailto:athenainterop@aol.com)
Password: TestPatient!@

You use your developer portal account only to register applications to get client id and secret.  You do not use your dev portal accounts to get authorized access to FHIR APIs in any athenaPractice or athenaFlow system.

**Comment by AjeetYadav07** [comment]
Closing this issue, since there is no further communication received. if you have any query, feel free to register a new ticket.
