### ISSUE TITLE
Payment Posting for Co-pay and unapplied credit.

### ISSUE THREAD

**Issue by satishjayakumar** [athenahealth/apiserver-athenaFlex#256]
1. Is there a way that I can post the Co-pay for a patient using $Posting API ?
2. As I see Visit Id is mandatory for payment posting, so the question is how do I post payment to unapplied credit ? 

Requirement is that, when a patient pays upfront amount for an upcoming surgery then that amount should not be posted to the charges of the previous visit but instead should be under unapplied credit so that it can used for the upcoming charges.

**Comment by Torin-Shepard-athena** [comment]
@satishjayakumar 
At this time, the POST $PostPayment API supports creating new payments that will be associated with only existing visits.  The concept of unapplied credit without  a link to a visit is not supported in this API.

We may consider this enhancement for a future release.

If athenaPractice was enhanced to allow creation of payments not yet associated with any visit, would it be acceptable to require human action in athenaPractice client application to associate the payment with a visit when the visit is created?  Or would your application also need FHIR Server enhancement to be able to use PUT requests to update existing payments to be able to add the association to a visit?

**Comment by AjeetYadav07** [comment]
@satishjayakumar,
Closing this issue, as no follow up question. If there are any query, please register a new issue.
