### ISSUE TITLE
Patient Emergency Contact and Pharmacy.

### ISSUE THREAD

**Issue by satishjayakumar** [athenahealth/apiserver-athenaFlex#258]
I checked the available APIs to fetch Patient Emergency contact details and Preferred Pharmacy, but I was not able to find the right one.

Could you please redirect me to the right APIs to fetch this data ?

**Comment by AjeetYadav07** [comment]
Patient contact information is present in RelatedPerson API.  Find devportal documentation for the same https://docs.mydata.athenahealth.com/fhir-r4/StructureDefinition-athena-relatedperson-profile.html

**Comment by Torin-Shepard-athena** [comment]
@satishjayakumar 
athenaPractice and athenaFlow do not yet support emergency contact or guardian as contact relationship types.  When this is available in a future release, the FHIR server can be enhanced to support these additional relationship type values.

Research is needed to determine the appropriate way for a FHIR Server to output the association between a Patient and one or more pharmacies.  The FHIR value sets for relationship types do not include pharmacy.  A pharmacy could be represented as a FHIR Organization which does not seem appropriate to be linked to a patient as a related _person_.  After deciding the proper way to represent multiple pharmacies for a patient, we then need to decide how to indicate which one is preferred.

**Comment by Torin-Shepard-athena** [comment]
http://community.fhir.org/t/how-can-we-send-patient-preferred-pharmacy/2439
This discussion thread suggests patient preferred pharmacy could be implemented in participant element of CareTeam resource with reference to the pharmacy represented as Organization resource.

This approach is not currently supported.  We may consider this in a future release.

**Comment by AjeetYadav07** [comment]
@satishjayakumar,
Since there are no follow up questions in this thread, marking as closed.
