### ISSUE TITLE
Binary Update fails for content type JPEG - "Unknown content type found for photo"

### ISSUE THREAD

**Issue by satishjayakumar** [athenahealth/apiserver-athenaFlex#259]
When we try to update the Binary with JPEG type, we are getting this error message - "Unknown content type found for photo".
I have attached the Request and the Response object for your reference.

Also in case of a new patient registration do we have an option to create a Binary ?

[BinaryUpdateResponse.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/10794732/BinaryUpdateResponse.txt)
[BinaryUpdateRequest.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/10794733/BinaryUpdateRequest.txt)

**Comment by Torin-Shepard-athena** [comment]
@satishjayakumar 
Please try changing the Binary request to have Base64-encoded value for Binary.data element.

**Comment by satishjayakumar** [comment]
I am still getting the same error when I tried with Base64 encoded value. I have attached the request.
Also, I do not see an option of Binary.Create. 
For a new patient we would want to upload a photo and then associate the Binary id to that patient, please let us know how we could achieve this.

[BinaryUpdateRequestBase64.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/10926389/BinaryUpdateRequestBase64.txt)

**Comment by satishjayakumar** [comment]
Team, Please let me know if there s any update on this ticket.

**Comment by deepaktiwari29** [comment]
Hello @satishjayakumar ,
Please let us know if you are still facing the same issue for the Binary update.
If yes, then please try changing Content-Type in request header to application/json+fhir

And for create operation, you can refer to issue #262

**Comment by deepaktiwari29** [comment]
Hello @satishjayakumar, Marking this issue as closed as there are no follow up questions. If there are any queries, please register a new issue.
