### ISSUE TITLE
Assessment Score Posting

### ISSUE THREAD

**Issue by satishjayakumar** [athenahealth/apiserver-athenaFlex#260]
We are looking for a suitable API to send the Assessment Score like PHQ9. Please let me know which API would be suitable for this.

From the scope of the access token, I can see QuestionnaireResponse.write API , but not sure how this can be implemented. Please provide any implementation document.

**Comment by Torin-Shepard-athena** [comment]
@satishjayakumar 
Please complete the [athenahealth API Integration Discovery Form.docx](https://github.com/athenahealth/apiserver-athenaFlex/files/10887211/athenahealth.API.Integration.Discovery.Form.docx) and email it to bjalbert@athenahealth.com and tshepard@athenahealth.com.  We can review your completed form and arrange a call to talk about possible options.

**Comment by AjeetYadav07** [comment]
@satishjayakumar,
Closing this issue, since not received any other queries in this thread from past 1 month.
