### ISSUE TITLE
License Restricted Data error in ValueSet/HDID

### ISSUE THREAD

**Issue by satishjayakumar** [athenahealth/apiserver-athenaFlex#261]
When we perform a GET on ValueSet/HDID, we are getting the below error message. But for the other ValueSet we are able to get the response.

"issue": [
    {
        "severity": "error",
        "code": "processing",
        "diagnostics": "License Restricted Data"
    }
]

**Comment by Torin-Shepard-athena** [comment]
@satishjayakumar 
HDID is the proprietary dictionary of observation terms in athenaPractice and athenaFlow.  Applications that write Observation resources can use LOINC codes that map to internal OBS terms.

#197 has more information

It may be possible to help you determine appropriate Observation codes If you describe your use case(s) for Observation resources.

**Comment by AjeetYadav07** [comment]
@satishjayakumar,
Marking this issue as closed.
