### ISSUE TITLE
How to incorporate the Login Widget into a patient-centered Flutter mobile app?

### ISSUE THREAD

**Issue by lukejavier** [athenahealth/apiserver-athenaFlex#265]
How do I authorize and implement the Athenahealth Login Widget on https://docs.athenahealth.com/api/guides/authorize-endpoint into my Flutter app? I have read the documentation but am unsure on how to begin.

I have sucessfully connected the athenaOne API into my app (200 success code after generating a 1-hour bearer access token on Postman using https://api.preview.platform.athenahealth.com/oauth2/v1/token and the OAuth 2.0 authorization on Postman) and have used a GET request for https://docs.athenahealth.com/api/api-ref/patient-appointment#Get-list-of-patient's-appointments and I can parse and display the data from the JSON response onto my Android emulator screen.

It is also asking for a redirect URI that starts with http, would that be athenahealth's login page URI since our mobile application is a Flutter app and coded in Dart.

**Comment by Torin-Shepard-athena** [comment]
@lukejavier 
This GitHub forum has information about FHIR APIs for athenaPractice and athenaFlow products.

Please post your question at https://docs.athenahealth.com/api/support to get help with athenaOne APIs.
