### ISSUE TITLE
Testing SMART App Launch

### ISSUE THREAD

**Issue by scarpenter** [athenahealth/apiserver-athenaFlex#267]
I'm attempting to test the SMART app launch sequence as described in #214.

Following the instructions in https://github.com/athenahealth/apiserver-athenaFlex/issues/214#issuecomment-970721282 I'm able to get a launch code back from the session create endpoint. The only thing I've done differently than those instructions is to use a hostname of `ap22sandbox.fhirapi.athenahealth.com` as that's what's referenced in the [docs for getting an access token](https://mydata.athenahealth.com/access-the-apis).

When I then construct the GET URL to to the authorize endpoint[0], the response is a page that displays "Oops!"[1] with no additional text or messages. Can anyone point me in the right direction for getting this authorize request to work correctly?

[0]`https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?client_id=our_client_id&state=defaultState&redirect_uri=https%3A%2F%2Four.domain.com%2Fathena%2Fauth%2Fcomplete&response_type=code%20id_token&response_mode=form_post&aud=https%3A%2F%2Fap22sandbox.fhirapi.athenahealth.com%2FdemoAPIServer%2Ffhir&disable_userselection=true&launch=cc760627-9f1a-4943-8edb-abb67aa9f14b&scope=offline_access%20openid%20profile%20user%2F*.read%20launch`
[1]
<img width="1945" alt="Screenshot 2023-03-16 at 4 06 37 PM" src="https://user-images.githubusercontent.com/83218/225740993-1f8f149c-9990-45d8-9449-c1f467f8a1dd.png">

**Comment by Torin-Shepard-athena** [comment]
@scarpenter 

Please try using /fhir/r4 as the audience for both launch session creation and the authorize URL.

Set aud value to "https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4" in the session/create request body.

Use aud=https%3A%2F%2Fap22sandbox.fhirapi.athenahealth.com%2FdemoAPIServer%2Ffhir%2Fr4 in the https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize URL.

**Comment by AjeetYadav07** [comment]
@scarpenter,
Making this issue as closed, if you have any query please raise a new ticket.
