### ISSUE TITLE
We are receiving CORS issue on one of our apps - Smart on FHIR App (Provider Facing App)

### ISSUE THREAD

**Issue by heenakhan19** [athenahealth/apiserver-athenaFlex#268]
**We are receiving CORS issue on one of our apps - Smart on FHIR App (Provider Facing App)** 

**Background Information -**

We have a backend script that gets the token and our frontend app utilizes the token generated and makes the FHIR call for searching the patient. While fetching the patient through the frontend app we get CORS issue.

**ERROR -**
Access to XMLHttpRequest at 'https://test.athenahealth.com/fhir/r4/Patient?ah-practice=Organization/a-1.Practice-195900&_count=1&family=doe&gender=female' from origin 'http://testIp:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Any guidelines on how to tackle this issue ?

Thanks

**Comment by Torin-Shepard-athena** [comment]
@heenakhan19 
I am sorry for the confusion between different athenahealth products.

This GitHUb repository has help for FHIR API integration with athenaPractice and athenaFlow.
 
Use the information at https://docs.athenahealth.com/api/ for API integration with athenaOne/athenaClinicals.
Please submit your issue at https://docs.athenahealth.com/api/support.

**Comment by heenakhan19** [comment]
Hi Torin,

I had a query on the FHIR API, on athena portal there is a field that talks about API access - so here we have option of Non-Certified API and Certified API, can you please help me understand what are the Non-Certified APIs. I did not find any documentation on that on the portal.

Thanks in Advance.

**Comment by Torin-Shepard-athena** [comment]
https://mydata.athenahealth.com has information about APIs for athenaPractice and athenaOne.

Please use athenaOne developer portal to get answers to that question.

https://docs.athenahealth.com/api/resources/complete_list_athena_apis
