### ISSUE TITLE
File Not Found - URL Paths on External Documents

### ISSUE THREAD

**Issue by mikeseale** [athenahealth/apiserver-athenaFlex#269]
I'm troubleshooting an issue that seems to have started with athenaPractice v22 where the FHIR API is no longer able to pull external documents with URLs for document paths. Here is the error we are getting on the FHIR server:

```
BCW356E06: File read/download failed for http://servername/Folder1/folder2/folder3/filename.pdf.
URL: https://ourfhirdns/ourfhirname/fhir/Binary/EXT-1996214168749350
java.io.FileNotFoundException: http:\servername\Folder1\folder2\folder3\filename.pdf (The filename, directory name, or volume label syntax is incorrect)
```
The main issue I see from this log snippet is that it is converting "http://" to "http:\\" and also all forward slashes have become backslashes. I'm not sure if this is an issue with the log or if the application has converted the path to something that is incorrect.

**Comment by Torin-Shepard-athena** [comment]
Thank you for raising awareness of this issue.  It appears to be a regression that will need to be fixed.  Target fix date is not yet available.

**Comment by deepaktiwari29** [comment]
@mikeseale
Closing the issue as we will address this in future release.
