### ISSUE TITLE
Reg. Certification Process

### ISSUE THREAD

**Issue by satishjayakumar** [athenahealth/apiserver-athenaFlex#270]
We have integrated FHIR API with our product. 
We would like to know what the process is before we start using these APIs in Production. 

Please share any documentation related to certification process.

**Comment by Torin-Shepard-athena** [comment]
@satishjayakumar 
#174  describes the process to move apps from athena API Sandbox to customer’s test and production environments. athenahealth does not have any certification or approval process for apps that use FHIR APIs to integrate with athenaPractice and athenaFlow.

In V22 and later versions, you must set your application to Production status and an athenaPractice or athenaFlow administrator must authorize your FHIR app in their system so it will be able to used the FHIR APIs.

**Comment by AjeetYadav07** [comment]
@satishjayakumar Marking this issue as closed.
